### ISSUE TITLE
Add android platform fails

### ISSUE THREAD

**Issue by Chirag-Chauhan** [AzureAD/azure-activedirectory-library-for-cordova#1]
I am using following command to add the Android platform: cordova platform add android@97718a0a25ec50fedf7b023ae63bfcffbcfafb4b. But it fails with error "Unable to fetch platform android@97718a0: Error: tunneling socket could not be established, cause=connect ECONNREFUSED".

On a side note, I am successfully able to add iOS platform.

Any help will be appreciated.

Thanks.

**Comment by sgrebnov** [comment]
Hi @Chirag-Chauhan, Android platform has been released so please try the following

`npm update -g cordova` to update to the latest Cordoav Tools
`cordova platform add android` - you don't need to specify version anymore

Feel free to re-open this issue if you still have a problem
