### ISSUE TITLE
tokenCacheItem does not persist in ios ?

### ISSUE THREAD

**Issue by HelenL75** [AzureAD/azure-activedirectory-library-for-cordova#101]
Hi,
I probably should post my question here instead of ADAL for objc.  I posted there because the issue only happens to ios devices, android is working fine.  I've also posted on stackoverflow because I desperately need some help to fix this problem.  I have the full description of the problem [here](http://stackoverflow.com/questions/39619309/adal-cordova-plugin-unable-to-retain-token-on-ios).

Thank you for your help~~

**Comment by sgrebnov** [comment]
Adding @vladimir-kotikov to help.

@HelenL75, is there any chance you can run generated Cordova ios platform (`<your-cordova-app>/platforms/ios`) using XCode? There will be detailed error trace available in XCode debug window after you made `acquireTokenAsync` call (something related to token cache write error).

The first thing to double check is that `com.microsoft.adalcache` is correctly added to the application access groups (similar to what is showed [here](https://docs.microsoft.com/en-us/intune/media/intune-app-sdk-ios-keychain-sharing.png)) - this is handled by the plugin, but still worth to double check that it works correct in case of remote build.

**Comment by HelenL75** [comment]
@sgrebnov, I will try to get XCode setup and provide that info when I get back to the office on Monday (not a very experienced Mac user...) . 

I also include my remote build log on dropbox [here](https://www.dropbox.com/s/jcn9uc8cpxkubqg/cordova-ios-remote-build-log.txt?dl=0) for you to review.  I saw some warning messages but not sure if that's something needs to be alarmed of.

Thank you so much for helping me investigate this problem.

**Comment by HelenL75** [comment]
@sgrebnov , I finally got the code compiled on a MacOS Mini and ran successfully on my iPhone 6s Plus.  It doesn't have the same issue of keep sending me back to login screen.  So this issue only happens with Remote Build then? Is there a way to get around this or I will always have to compile my ios version on a Mac?

**Comment by nguyenjk** [comment]
@sgrebnov, I have similar issue. I have ionic app and I followed this [sample](https://github.com/Azure-Samples/active-directory-cordova-multitarget). The login window keeps pop up. I checked and found com.microsoft.adalcache is added. The token seems to be empty all the time. I build the project on mac and when I run on emulator, it seems always failed to save the token into the cache. any idea what i am missing?

**Comment by vladimir-kotikov** [comment]
@nguyenjk, when you running app from XCode, are there any messages logged to console when you are authenticating?

**Comment by nguyenjk** [comment]
@vladimir-kotikov, I found the issue. I have to assigned the project to be under some team development in order to get key sharing work. I open Xcode manually, and click in the ionic iOS project. under general tab, there is sign in section and choose the team you want to sign in. That would resolve my issue.

**Comment by vladimir-kotikov** [comment]
Ah, I see. This is a known issue - to build and run app from Cordova CLI you can use a [`--developmentTeam` command line option or `developmentTeam` field in `build.json`](https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html#using-flags) if you're on cordova-ios@4.3.0 or use a [hook](http://www.dpogue.ca/articles/cordova-xcode8.html) if you haven't yet upgraded your cordova-ios

**Comment by candril** [comment]
@vladimir-kotikov that's exactly what I'm doing (setting the the team ID in the build.json).
However, it works from a build made with xCode.
It's **not** working for a build done with `cordova build ios --device` => `acquireTokenSlientAsync` is saying that no login exists.

I've checked the entitlements in xcode, they seem to be fine.

**Comment by candril** [comment]
@vladimir-kotikov do you have any updates on this? Thanks.
