### ISSUE TITLE
ADAL android upgrade to source version - 1.10.0

### ISSUE THREAD

**Issue by ramaguduri** [AzureAD/azure-activedirectory-library-for-cordova#104]
### ADAL android version not latest

Current version of the ADAL android is 1.1.18 which is 6 months old and there have been good number of fixes made and the latest release is 1.10.0
### Repro Environment Details
1. Installed plugin version:  master or 0.8.1
2. Target Platform: Android

**Comment by khalidaw** [comment]
Opened PR for this: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/pulls

**Comment by khalidaw** [comment]
+1
I have upgraded to 1.10 in our code.
A lot of key generating errors are solved there.

**Comment by vladimir-kotikov** [comment]
Linking #112

**Comment by vladimir-kotikov** [comment]
#112 has been merged, so closing this one
