### ISSUE TITLE
the afterinstall script for android refers to old minimum sdk

### ISSUE THREAD

**Issue by EeKay** [AzureAD/azure-activedirectory-library-for-cordova#11]
The script afterPluginInstall-android.js sets the android:minSdkVersion to 14 for the manifest file.
This in its turn triggers the build to include the android-support-v4.jar file.

When using a library that depends on the newer v13 support jar this will create "Multiple Dex included" issues like:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;

(see issues with Pushplugin like https://github.com/phonegap-build/PushPlugin/issues/492)

Setting the minimum to sdk 18 or higher fixes this and lets the build continue again. could we crank this number up so issues in conjunction with popular plugins like Pushplugin wont break the build?

**Comment by sgrebnov** [comment]
PS. I believe starting from cordova-android@4.1.0 platform already uses minSdkVersion 14 so `afterPluginInstall-android.js` is not required anymore at all. (if you don't plan to use this plugin w/ older versions)

**Comment by sgrebnov** [comment]
Taking into account we still support `cordova-android@4.0` which uses older min sdk version we still need this functionality. You can always set required min sdk version for Android via `config.xml` (hook script  don't override this setting if it presents).
I'll update this after we drop cordova-android < 4.1 support
