### ISSUE TITLE
Azure B2C support with apache cordova

### ISSUE THREAD

**Issue by sowsan** [AzureAD/azure-activedirectory-library-for-cordova#110]
Is there a support for Azure B2C ?

Regards,
Sowmyan

**Comment by kabaehr** [comment]
Hey, I am just a person who used this plugin for Azure B2C. It worked well except one Issue: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/109

**Comment by sowsan** [comment]
Are you able to setup the AD B2C policy and send the details ?

**Comment by kabaehr** [comment]
I setup a policy and send it with the token request. What details do you mean?

**Comment by vladimir-kotikov** [comment]
@sowsan, @kabaehr, closing this in favor of #85
