### ISSUE TITLE
Certificate error on Android causing log in screen to fail to display

### ISSUE THREAD

**Issue by emrdev** [AzureAD/azure-activedirectory-library-for-cordova#111]
### Issue Description
We have noticed a problem on a couple of Android handsets - a user clicks the sign in button in our app which invokes the ADAL plugin "acquireTokenAsync" method. The screen dims briefly and then the user is sent back to the sign in screen (as the call failed). 

### Repro Environment Details
1. Plugin version 0.7.1, I have also tried 0.8.1
2. Android version - seen on 5.0.2 and 6.0.1
3. Test device Samsung J3
4. Using TACO - but same result when building via vanilla cordova

On 1 development device which was working I performed a Software Update - and then the issue appeared - I then did a factory reset and re-installed our app and the issue went away. 

In the device log we can see the following around the point of failure:

11-29 17:00:01.377 31175 31175 V AuthenticationContext: 2016-11-29 23:00:01-8daf46bf-2594-47af-900d-3a5b080953b7-Get waiting request: 138475221 ver:1.1.18

11-29 17:00:01.377 31175 31175 V AuthenticationContext: 2016-11-29 23:00:01-8daf46bf-2594-47af-900d-3a5b080953b7-onActivityResult RequestId:138475221 ver:1.1.18

11-29 17:00:01.377 31175 31175 V AuthenticationContext: 2016-11-29 23:00:01-8daf46bf-2594-47af-900d-3a5b080953b7-Error info:Code:-11 primary error: 5 certificate: Issued to: CN=secure.aadcdn.microsoftonline-p.com,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US;

11-29 17:00:01.377 31175 31175 V AuthenticationContext: Issued by: CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US;

11-29 17:00:01.377 31175 31175 V AuthenticationContext:  on URL: https://secure.aadcdn.microsoftonline-p.com/ests/2.1.5133.5/content/cdnbundles/jquery.1.11.min.js for requestId: 138475221 CorrelationId: a1bbbdb7-c628-449b-a6dd-6c2bc598eff7 ver:1.1.18

11-29 17:00:01.382 31175 31175 V AuthenticationContext: 2016-11-29 23:00:01-8daf46bf-2594-47af-900d-3a5b080953b7-Sending error to callback CorrelationId: a1bbbdb7-c628-449b-a6dd-6c2bc598eff7 ver:1.1.18

11-29 17:00:01.382 31175 31175 V AuthenticationContext: 2016-11-29 23:00:01-8daf46bf-2594-47af-900d-3a5b080953b7-Remove waiting request: 138475221 ver:1.1.18

We also see the following:

11-29 17:00:01.567 31175 31175 E BasicWebViewClient: ERROR_FAILED_SSL_HANDSHAKE:2016-11-29 23:00:01-8daf46bf-2594-47af-900d-3a5b080953b7-Received ssl error ver:1.1.18

**Comment by emrdev** [comment]
Here's some version details that have been captured from 2 working and 2 failing devices

![android_sheet](https://cloud.githubusercontent.com/assets/17826621/20791333/54d3df76-b7b4-11e6-97a4-519bcec8deef.PNG)

**Comment by Eqbalazar** [comment]
For me was the same . I unistalled the updated version of System Webview and set to default .Now is good.
System WebView Vesion: 49.0.2623.105

**Comment by puneetagarwal** [comment]
I am also facing the same problem in my Moto G4. When I try to open the login screen, it appears and disappearing within a second. 

Hey @Eqbalazar, How do you able to uninstall the updated version of System Webview as in my device, it just shows "Force stop" and "Disable" button. Is it possible to catch this error in the code as I can't see any linking between the error and my code?

Thanks.

**Comment by Eqbalazar** [comment]
Hey , 
After Disable you can uninstall it .

**Comment by puneetagarwal** [comment]
Hey @Eqbalazar, Thank you very much, it worked for me. :)

But, is there any way to catch this error in the code as to display a proper message to the user if he/she is facing this issue in their phones?

**Comment by matrosov-nikita** [comment]
@Eqbalazar, @puneetagarwal, could you please provide your versions of android, target sdk, ADAL?

**Comment by lightwaxx** [comment]
Can someone please fix this issue.
Android version - 5.1.1

**Comment by puneetagarwal** [comment]
Hey @matrosov-nikita, I am running my application on Android 6.0.1 (Marshmallow), the target SDK is 25 and ADAL library version is 1.1.3. Is it possible to catch this error?

Thanks.

**Comment by vladimir-kotikov** [comment]
@puneetagarwal, we currently use ADAL v1.1.18 - are you using old version of the plugin? If so, consider updating to the newest version.

@Eqbalazar, @puneetagarwal, @lightwaxx, it also worth trying #112 to see if newer ADAL for Android would resolve the issue. If it doesn't help, I doubt we could do anything here, because this seems tobe an issue with either native ADAL or system WebView, which both are out of our control.

You might also want to file an issue in https://github.com/AzureAD/azure-activedirectory-library-for-android - it might be that Android ADAL devs aware of this problem or might suggest a workaround

**Comment by Eqbalazar** [comment]
Hello All , 

Mine is Android 6.0.1 ,  targetSdkVersion 21 , Adal version com.microsoft.aad:adal:1.2.0 .
 I got error on native App. It seems **developer does not have option to control this for now** .
 You can see the source code of library : 



abstract class BasicWebViewClient extends WebViewClient {
    private static final String TAG = "BasicWebViewClient";

    public static final String BLANK_PAGE = "about:blank";

    private final String mRedirect;
    private final AuthenticationRequest mRequest;
    private final Context mCallingContext;
    private final UIEvent mUIEvent;

    public BasicWebViewClient(final Context appContext, final String redirect,
                              final AuthenticationRequest request, final UIEvent uiEvent) {
        mCallingContext = appContext;
        mRedirect = redirect;
        mRequest = request;
        mUIEvent = uiEvent;
    }

    public abstract void showSpinner(boolean status);

    public abstract void sendResponse(int returnCode, Intent responseIntent);
    
    public abstract void cancelWebViewRequest();
    
    public abstract void prepareForBrokerResumeRequest();
    
    public abstract void setPKeyAuthStatus(boolean status);
    
    public abstract void postRunnable(Runnable item);    

    @Override
    public void onReceivedHttpAuthRequest(WebView view, final HttpAuthHandler handler,
            String host, String realm) {

        // Create a dialog to ask for creds and post it to the handler.
        Logger.i(TAG, "onReceivedHttpAuthRequest for host:" + host, "");
        mUIEvent.setNTLM(true);

        HttpAuthDialog authDialog = new HttpAuthDialog(mCallingContext, host, realm);

        authDialog.setOkListener(new HttpAuthDialog.OkListener() {
            public void onOk(String host, String realm, String username, String password) {
                Logger.i(TAG, "onReceivedHttpAuthRequest: handler proceed" + host, "");
                handler.proceed(username, password);
            }
        });

        authDialog.setCancelListener(new HttpAuthDialog.CancelListener() {
            public void onCancel() {
                Logger.i(TAG, "onReceivedHttpAuthRequest: handler cancelled", "");
                handler.cancel();
                cancelWebViewRequest();
            }
        });

        Logger.i(TAG, "onReceivedHttpAuthRequest: show dialog", "");
        authDialog.show();
    }
    
    @Override
    public void onReceivedError(WebView view, int errorCode, String description, String failingUrl) {
        super.onReceivedError(view, errorCode, description, failingUrl);
        showSpinner(false);
        Logger.e(TAG, "Webview received an error. Errorcode:" + errorCode + " " + description, "",
                ADALError.ERROR_WEBVIEW);
        Intent resultIntent = new Intent();
        resultIntent.putExtra(AuthenticationConstants.Browser.RESPONSE_ERROR_CODE, "Error Code:"
                + errorCode);
        resultIntent.putExtra(AuthenticationConstants.Browser.RESPONSE_ERROR_MESSAGE, description);
        resultIntent.putExtra(AuthenticationConstants.Browser.RESPONSE_REQUEST_INFO, mRequest);
        sendResponse(AuthenticationConstants.UIResponse.BROWSER_CODE_ERROR, resultIntent);
    }

    @Override
    public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
        // Developer does not have option to control this for now
        super.onReceivedSslError(view, handler, error);
        showSpinner(false);
        handler.cancel();
        Logger.e(TAG, "Received ssl error", "", ADALError.ERROR_FAILED_SSL_HANDSHAKE);
        Intent resultIntent = new Intent();
        resultIntent.putExtra(AuthenticationConstants.Browser.RESPONSE_ERROR_CODE, "Code:"
                + ERROR_FAILED_SSL_HANDSHAKE);
        resultIntent.putExtra(AuthenticationConstants.Browser.RESPONSE_ERROR_MESSAGE,
                error.toString());
        resultIntent.putExtra(AuthenticationConstants.Browser.RESPONSE_REQUEST_INFO, mRequest);
        sendResponse(AuthenticationConstants.UIResponse.BROWSER_CODE_ERROR, resultIntent);
    }

    @Override
    public void onPageFinished(WebView view, String url) {
        super.onPageFinished(view, url);

        /*
         * Once web view is fully loaded,set to visible
         */
        view.setVisibility(View.VISIBLE);
        if (!url.startsWith(BLANK_PAGE)) {
            showSpinner(false);
        }
    }

    @Override
    public void onPageStarted(WebView view, String url, Bitmap favicon) {
        logPageStartLoadingUrl(url);
        super.onPageStarted(view, url, favicon);
        showSpinner(true);
    }

    private void logPageStartLoadingUrl(final String url) {
        if (TextUtils.isEmpty(url)) {
            Logger.v(TAG, "onPageStarted: Null url for page to load.");
            return;
        }

        final Uri uri = Uri.parse(url);
        if (uri.isOpaque()) {
            Logger.v(TAG, "onPageStarted: Non-hierarchical loading uri: " + url);
            return;
        }

        if (StringExtensions.isNullOrBlank(uri.getQueryParameter(
                AuthenticationConstants.OAuth2.CODE))) {
            Logger.v(TAG, "Webview starts loading: " + uri.getHost() + uri.getPath(),
                    "Full loading url is: " + url, null);
        } else {
            Logger.v(TAG, "Webview starts loading: " + uri.getHost() + uri.getPath()
                    + " Auth code is returned for the loading url.");
        }
    }

    @Override
    //Give the host application a chance to take over the control when a new url is about to be loaded in the current WebView.
    public boolean shouldOverrideUrlLoading(final WebView view, String url) {
        Logger.v(TAG, "Navigation is detected");
        if (url.startsWith(AuthenticationConstants.Broker.PKEYAUTH_REDIRECT)) {
            Logger.v(TAG, "Webview detected request for pkeyauth challenge.");
            view.stopLoading();
            setPKeyAuthStatus(true);
            final String challengeUrl = url;
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        ChallengeResponseBuilder certHandler = new ChallengeResponseBuilder(
                                new JWSBuilder());
                        final ChallengeResponse challengeResponse = certHandler
                                .getChallengeResponseFromUri(challengeUrl);
                        final Map<String, String> headers = new HashMap<>();
                        headers.put(AuthenticationConstants.Broker.CHALLENGE_RESPONSE_HEADER,
                                challengeResponse.getAuthorizationHeaderValue());
                        postRunnable(new Runnable() {

                            @Override
                            public void run() {
                                String loadUrl = challengeResponse.getSubmitUrl();
                                Logger.v(TAG, "Respond to pkeyAuth challenge", "Challenge submit url:" 
                                        + challengeResponse.getSubmitUrl(), null);
                                view.loadUrl(loadUrl, headers);
                            }
                        });
                    } catch (AuthenticationServerProtocolException e) {
                        Logger.e(TAG, "Argument exception", e.getMessage(),
                                ADALError.ARGUMENT_EXCEPTION, e);
                        // It should return error code and finish the
                        // activity, so that onActivityResult implementation
                        // returns errors to callback.
                        Intent resultIntent = new Intent();
                        resultIntent.putExtra(
                                AuthenticationConstants.Browser.RESPONSE_AUTHENTICATION_EXCEPTION,
                                e);
                        if (mRequest != null) {
                            resultIntent.putExtra(
                                    AuthenticationConstants.Browser.RESPONSE_REQUEST_INFO,
                                    mRequest);
                        }
                        sendResponse(
                                AuthenticationConstants.UIResponse.BROWSER_CODE_AUTHENTICATION_EXCEPTION,
                                resultIntent);
                    } catch (AuthenticationException e) {
                        Logger.e(TAG, "It is failed to create device certificate response",
                                e.getMessage(), ADALError.DEVICE_CERTIFICATE_RESPONSE_FAILED, e);
                        // It should return error code and finish the
                        // activity, so that onActivityResult implementation
                        // returns errors to callback.
                        Intent resultIntent = new Intent();
                        resultIntent.putExtra(
                                        AuthenticationConstants.Browser.RESPONSE_AUTHENTICATION_EXCEPTION,
                                        e);
                        if (mRequest != null) {
                            resultIntent.putExtra(
                                    AuthenticationConstants.Browser.RESPONSE_REQUEST_INFO,
                                    mRequest);
                        }
                        sendResponse(
                                AuthenticationConstants.UIResponse.BROWSER_CODE_AUTHENTICATION_EXCEPTION,
                                resultIntent);
                        }
                }
            }).start();

            return true;
        } else if (url.toLowerCase(Locale.US).startsWith(mRedirect.toLowerCase(Locale.US))) {
            Logger.v(TAG, "Navigation starts with the redirect uri.");
            if (hasCancelError(url)) {
                // Catch WEB-UI cancel request
                Logger.i(TAG, "Sending intent to cancel authentication activity", "");
                view.stopLoading();
                cancelWebViewRequest();
                return true;
            }
            
            processRedirectUrl(view, url);
            return true;
        } else if (url.startsWith(AuthenticationConstants.Broker.BROWSER_EXT_PREFIX)) {
            Logger.v(TAG, "It is an external website request");
            openLinkInBrowser(url);
            view.stopLoading();
            cancelWebViewRequest();
            return true;
        } else if (url.startsWith(AuthenticationConstants.Broker.BROWSER_EXT_INSTALL_PREFIX)) {
            Logger.v(TAG, "It is an install request");
            ApplicationReceiver.saveRequest(mCallingContext, mRequest, url);
            HashMap<String, String> parameters = StringExtensions
                    .getUrlParameters(url);
            prepareForBrokerResumeRequest();
            // Having thread sleep for 1 second for calling activity to receive the result from 
            // prepareForBrokerResumeRequest, thus the receiver for listening broker result return
            // can be registered. openLinkInBrowser will launch activity for going to
            // playstore and broker app download page which brought the calling activity down 
            // in the activity stack.
            final int threadSleepForCallingActivity = 1000;
            try {
                Thread.sleep(threadSleepForCallingActivity);
            } catch (InterruptedException e) {
                Logger.v(TAG + ":shouldOverrideUrlLoading", "Error occured when having thread sleeping for 1 second");
            }
            openLinkInBrowser(parameters.get(ApplicationReceiver.INSTALL_URL_KEY));
            view.stopLoading();
            return true;
        }

        return processInvalidUrl(view, url);
    }
    
    public abstract void processRedirectUrl(final WebView view, String url);

    public abstract boolean processInvalidUrl(final WebView view, String url);

    final Context getCallingContext() {
        return mCallingContext;
    }
    
    protected void openLinkInBrowser(String url) {
        String link = url
                .replace(AuthenticationConstants.Broker.BROWSER_EXT_PREFIX, "https://");
        Intent intent = new Intent(Intent.ACTION_VIEW, Uri.parse(link));
        mCallingContext.startActivity(intent);
    }
    
    private boolean hasCancelError(String redirectUrl) {
        Map<String, String> parameters = StringExtensions.getUrlParameters(redirectUrl);
        String error = parameters.get("error");
        String errorDescription = parameters.get("error_description");

        if (!StringExtensions.isNullOrBlank(error)) {
            Logger.w(TAG, "Cancel error:" + error, errorDescription, null);
            return true;
        }

        return false;
    }
}

**Comment by vladimir-kotikov** [comment]
From AzureAD/azure-activedirectory-library-for-android#759 this is a known issue with Android WebView, see https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/SSL-Certificate-Validation-Issue

**Comment by jmkwok** [comment]
Does this mean that once Chrome is updated to version 54, Symantec sites will work continuously? Or will the user have to update Chrome AGAIN after 10 weeks?

**Comment by vladimir-kotikov** [comment]
@jmkwok, it's not very clear to me as well, but I'm inclined to the 1st variant

**Comment by khalidaw** [comment]
Android system webview should be updated also.
