### ISSUE TITLE
Cannot submit to the Windows store

### ISSUE THREAD

**Issue by filionf** [AzureAD/azure-activedirectory-library-for-cordova#114]
### Issue Description
I added Azure AD authentication to my app using cordova-plugin-ms-adal. It works well, but when submitting the package to the Windows Store, I receive the following error: 

> You cannot submit pre-compiled .NET Native packages.

Also, when building it, I receive the following:

> C:\Program Files (x86)\MSBuild\Microsoft.NetNative\x64\ilc\IlcInternals.targets(934,5): warning : Your application is missing a Runtim e Directives (rd.xml) file. Runtime Directives are used to describe the dynamic behavior of your application and control the .NET Native optimizer. It is recommended to have at least one rd.xml file in your project. [C:\dev\projects\first\platforms\windows\CordovaApp.Wi ndows10.jsproj]

I am not quite sure how to test this because it fails when uploading the package, removing the plugin works.

### Repro Environment Details
1. Installed plugin version: 
`0.8.1`
2. Target Platform: 
`Windows 10`
3. Test device and OS version: 
`Build for x86, x64 & ARM`
4. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version? 
Package created using the following command with cordova 6.4.0 `cordova build windows --release --device -- --win --bundle --archs="x86 x64 arm"`

**Comment by daserge** [comment]
@filionf try uploading `*bundle.appxupload` file instead of `appxbundle` - it's located one directory up (in `\platforms\windows\AppPackages\`).

**Comment by filionf** [comment]
Ah ha! It looks like it does not get generated. Might not be related with this plugin at all finally. I will investigate and post back. Thanks for the hint.

**Comment by filionf** [comment]
Finally got it working. To generate the appxupload, I had to modify the buid.js of cordova-windows with `UapAppxPackageBuildMode = "StoreUpload"`
@daserge, since you seem to be working on cordova-windows, is this something I should submit a PR for? Or it has already been taken care of for the next release of cordova-windows?

**Comment by daserge** [comment]
@filionf - could you please tell which cordova-windows platform version has this issue?
I could not reproduce this with 4.5.0-dev (Github master).
We should file it at http://issues.cordova.io.

**Comment by filionf** [comment]
Oh, sorry, I forgot to mention. I reproduce it using 4.4.3, but I noticed the code changed in dev where I had to change it, that is why I ask, it might have been solved differently.

In build.js, here is what I changed to make it work.

    if (shouldBundle && index === configsArray.length - 1) {
        otherProperties.CordovaBundlePlatforms = bundleTerms;
        otherProperties.UapAppxPackageBuildMode = "StoreUpload";
    } else if (shouldBundle) {
        otherProperties.CordovaBundlePlatforms = build.arch;
    }

**Comment by daserge** [comment]
@filionf thanks for the details.
It's strange but it does not reproduce for me with 4.4.3 - I might be missing some steps - could you please elaborate?
Are you associating with Store using Visual Studio?
Also - does it work for you with master version? (`cordova platform add https://github.com/apache/cordova-windows`)

**Comment by filionf** [comment]
@daserge Doing the same with the master version.
It was not associated with the Store using Visual Studio because I re-added the platform from scratch, but same result after associating it. Is it possible that what you are missing is the Windows 10? Because I remember the file got generated when building for Windows 8.1, on my setup, it is set using the config.xml file, but I believe you can pass it to cordova as well.
I also have the latest Visual Studio 2015 (14.0.25431.01 Update 3)

`cordova build windows --release --device -- --win --bundle --uap --archs="x86 x64 arm"`

**Comment by daserge** [comment]
@filionf Bingo, thanks!
Looks like it's a [known issue](https://blogs.msdn.microsoft.com/wsdevsol/2016/01/08/windows-store-app-projects-stopped-generating-the-appxupload-file-after-installing-vs-2015-update-1/) we have obviously missed.
Filed [[Windows] bundle.appxupload not generated for Windows 10 target](https://issues.apache.org/jira/browse/CB-12298).

**Comment by filionf** [comment]
I will close this one since it is not really related to ADAL after all! Love your work-around. I did not know we could do that.
Thank you!
