### ISSUE TITLE
Windows - acquireTokenSilentAsync doesn't retrieve a token when provided with userId

### ISSUE THREAD

**Issue by almost92** [AzureAD/azure-activedirectory-library-for-cordova#119]
when using the plugin in a Windows app, calling acquireTokenSilentAsync with userId parameter fails with error message "failed_to_acquire_token_silently - Failed to acquire token silently. Call method AcquireToken."
for Android and iOS sending userID returns a valid token.
as a workaround (for windows) I am currently sending undefined instead of userId.

Repro Environment Details
1.	Installed plugin version: 0.8.1
2.	Target Platform: Windows 10
3.	Test device and OS version: Lumia 930 , 1607 (build 10.0.14393.448)
4.	Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version? command line
5.	If Windows related, please specify whether SSO option is enabled or not. SSO not enabled

**Comment by vladimir-kotikov** [comment]
@almost92, could you please check if #120 solves your issue?

**Comment by almost92** [comment]
@vladimir-kotikov works like a charm.
thanks a lot guys.

**Comment by vladimir-kotikov** [comment]
Nice! Thanks for verification!
