### ISSUE TITLE
Corporate ADFS support for Windows Phone 8.1 - When?

### ISSUE THREAD

**Issue by arefkn** [AzureAD/azure-activedirectory-library-for-cordova#12]
Hello,

Can you please brief on the issue and the timeline for enabling this on Win P 8.1?

**Comment by kromkens** [comment]
Any news on adding Windows Phone 8.1 support yet? Or maybe how to enable it by code?

**Comment by kromkens** [comment]
Just support for ADFS servers, not SSO.

**Comment by RandalliLama** [comment]
@arefkn @kromkens It should already support ADFS.  You will need to pass 'false' to the validateAuthority parameter of the AuthenticationContext, however.
