### ISSUE TITLE
Microsoft is not defined is coming in run time exception

### ISSUE THREAD

**Issue by ersurajnegi** [AzureAD/azure-activedirectory-library-for-cordova#123]
### Issue Description
Problem description...

### Repro Environment Details
1. Installed plugin version:  (Have you tried installing the latest plugin version to ensure this has not already  been fixed?)
2. Target Platform: for example, `Android` or `Windows 10` or `Windows Phone 8.1`
3. Test device and OS version: for example, `Nexus 5 Android 6.0`, `Windows Mobile 10 emulator`, `Windows 8.1 Desktop x64`
4. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version?
3. If Windows related, please specify whether SSO option is enabled or not.

**Comment by daserge** [comment]
Hi @ersurajnegi could you please add some details about the issue?

**Comment by daserge** [comment]
Is the issue about transpile or runtime error?
In the first case try adding `declare var Microsoft: any;`.

**Comment by vladimir-kotikov** [comment]
@ersurajnegi, is this still actual? Closing this for now as there was no response from your side, but in case if it's still actual, please reopen and provide additional details, so we can investigate
