### ISSUE TITLE
Cordova windows app closes immediately due to JavaScript runtime error: Unable to get property 'setUseBroker' of undefined or null reference

### ISSUE THREAD

**Issue by lightwaxx** [AzureAD/azure-activedirectory-library-for-cordova#124]
Target = Windows Phone 8.1
Cordova IDE = Visual Studio

Why am I getting the below error on Visual studio. I tried adding the winstore-jscompat.js file and this has not help. The app closes immediately on start up. I built the app using Cordova CLI tool but I needed to debug the windows version and I couldn't find a suitable platform, so I had to (grudgingly) turn to VS

![image](https://cloud.githubusercontent.com/assets/861288/22252759/468ff4e6-e260-11e6-80a0-5c54691b17c6.png)

**Comment by daserge** [comment]
@lightwaxx `AuthenticationSettings.setUseBroker` is supported on [Android only](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/a006b45f17a02f63bd2dbc914b431445e8ecbe6c).

**Comment by daserge** [comment]
Fixed in #125 - `AuthenticationSettings.setUseBroker` is now available across platforms.
Note that `setUseBroker` is still functional on Android platform only as Windows and iOS handle Broker internally.
