### ISSUE TITLE
Cancel on password reset page returns cached token

### ISSUE THREAD

**Issue by balanb02** [AzureAD/azure-activedirectory-library-for-cordova#136]
Hi,

I am using the Adal Cordova library to get the token from the Azure AD Server for my Android and iOS app and it works.  However, there is one scenario which baffles me.

The first time the user tries to login, I use the user id to try to acquire a token using authContext.acquireTokeAsync() and it works fine.  Now, once the user logs out of the app and then logs in again, I want to force the user to go to the Microsoft login page.  Hence I call acquireTokenAsync as I would for a new user login and this shows the Microsoft login page.  This time instead of entering userid and password, I click the “Forgot password” link and when the reset password page appears, I hit cancel.  I assume that this means that I did not enter a valid password yet.

However, I see that the token is returned in this particular case too.  The token returned may be picked up from the token cache, but I am calling authContext.tokenCache.clear() before calling acquireTokenAsync.  In any case, shouldn’t showing the Azure login page clear out the cached token for the user?  I am not sure what the best way to deal with this situation is.

Please advise.
Thanks!
### Repro Environment Details
1. Installed plugin version:  0.8.1
2. Target Platform: Android or iOS
3. Test device and OS version: `Multiple devices with Android`, `iOS simulator`

**Comment by vladimir-kotikov** [comment]
@balanb02, thanks for reporting!

A culprit of this seems to be session cookies, left by authentication service in the WebView. Usually, when calling `acquireTokenAsync` ADAL instructs server to ignore these cookies by adding a special query parameter to login URL.
However in this particular case after hitting "Cancel" button password reset page redirects web view to a slightly different URL which causes server to accept these stored cookies.

This is something we can't fix on our side. As of now the only workaround I can suggest - clear session cookies after signing user out (in addition to clearing token cache) as suggested in README: https://github.com/AzureAD/azure-activedirectory-library-for-cordova#how-to-sign-out

**Comment by balanb02** [comment]
Thanks! That seems to work.

**Comment by vladimir-kotikov** [comment]
Okay, thanks for confirmation. Closing this as there is not much we can do. Feel free to reopen in case if there are any other related problems.
