### ISSUE TITLE
Adal authentication error on iOS 8.3

### ISSUE THREAD

**Issue by SanjibK** [AzureAD/azure-activedirectory-library-for-cordova#138]
I am using adal for authentication in cordova ios project. App seems working fine on iOS 9+. But whenever trying to build on iOS 8.3 simulator or device I am getting below error and authentication fails. 

**ADALiOS ERROR: authorization error. Additional Information: The operation was cancelled.. ErrorCode: 3072
ADALiOS ERROR: Error raised: 3072. Additional information: Domain: NSCocoaErrorDomain ProtocolCode: (null) Details: The operation was cancelled.. ErrorCode: 3072**

However there is no issue with build and compilation on any platform. App is loading properly until login after which its fails to generate required Tokens and other dependent services are getting hampered due to this. I added com.microsoft.adalcache in keychain group also still getting the same error.
List of plugins with versions are,
cordova-plugin-ms-adal 0.9.0 "ADAL for Cordova"
Cordova 6.1.0
cordova ios 4.1.1
HockeyApp 2.2.3
Xcode Version 8.3 beta 2
Base SDK iOS 10.3

iOS deploment target has been kept for iOS 8.0. Is it due to version mismatch among plugins or some Xcode setting related error? Please advice

**Comment by vladimir-kotikov** [comment]
@SanjibK, thank you for reporting. We'll try to reproduce the problem and report back once there is a repro. Also, just curious, have you tried to build/run app using non-preview Xcode version? It's possible that beta might be a cause here.

**Comment by SanjibK** [comment]
There was some plugin version mismatch. I upgraded all related plugins including Cordova. Besides one JS method (startsWith()) was failing on iOS 8 devices. After a little bit minor adjustment on Xcode it's finally working now. Thanks.

**Comment by ashish-iitr** [comment]
Hi @SanjibK even I am getting the same error, could you please tell what exactly you did to resolve this issue?
