### ISSUE TITLE
Bad Request – Request Too Long

### ISSUE THREAD

**Issue by toveram** [AzureAD/azure-activedirectory-library-for-cordova#142]
Getting the below error in Android platform.

“Bad Request – Request Too Long”
“HTTP Error 400.  The size of the request headers is too long.”

**Comment by matrosov-nikita** [comment]
@toveram, could you please provide more information about your case?
What AD-specific setting do you use?
What acquisition type are using when you get this error?
Also it'd be very helpful if you could run and post here result of `adb logcat` command.

For now, I guess that this issue may be related to length of the cookie header or there are server request limitations. Could you please try the [following steps](https://github.com/AzureAD/azure-activedirectory-library-for-cordova#how-to-sign-out) to clean up your cache items?

**Comment by matrosov-nikita** [comment]
@toveram, just a friendly ping.
