### ISSUE TITLE
accessTokenType undefined

### ISSUE THREAD

**Issue by aqib1604** [AzureAD/azure-activedirectory-library-for-cordova#143]
```
var me = this;
                var authContext = new Microsoft.ADAL.AuthenticationContext("https://login.windows.net/common");
                authContext.acquireTokenSilentAsync("https://graph.windows.net", "client_id")
                  .then(function(authResponse) {
                      console.log(authResponse);
                    console.log("Token acquired: " + authResponse.accessToken);
                    console.log("Token will expire on: " + authResponse.expiresOn);
                    UcwaData.authToken = "Bearer "+authResponse.accessToken;
                    UcwaData.authExpires = UcwaUtilities.getExpiry(authResponse.expiresOn);
                    me.authenticate().then(
                            (success) => {
                                resolve(success)
                            },
                            (error) => {
                                reject(error)
                            }
                        );

                  }, function(err) {

                    console.log("Failed to authenticate: " + err);
                    authContext.acquireTokenAsync("https://graph.windows.net", "client_id", "https://login.microsoftonline.com/common/oauth2/nativeclient")
                    .then(function(res){
                        console.log(res);
                        console.log("Token acquired: " + res.accessToken);
                        console.log("Token will expire on: " + res.expiresOn); 
                        UcwaData.authToken = "Bearer "+res.accessToken;
                        UcwaData.authExpires = UcwaUtilities.getExpiry(res.expiresOn);
                        me.authenticate().then(
                            (success) => {
                                resolve(success)
                            },
                            (error) => {
                                reject(error)
                            }
                        );  
                    }, function (err) {
                        console.log(new Date().toLocaleString()+" Failed to authenticate: " + err);
                    });
                  });
```

I am using above code to aquire access token. although I get token but accessTokenType is undefined. When I use access token with hard coded "Bearer" I am getting wrong credentials error in below code.

Can anyone help me please.
```
return new Promise(
            (resolve, reject) => {
                var headers: Headers = new Headers();

                headers.set("Accept", "application/json");
                headers.set("Authorization", UcwaData.authToken);

                var options: RequestOptionsArgs = {
                    withCredentials: true,
                    method: RequestMethod.Get,
                    headers: headers
                };
                console.log(UcwaData.discoveryHref);
                var subscription = UcwaSimple.http.request(UcwaData.discoveryHref, options).subscribe(
                    (httpResponseOK: any) => {
                        console.log("UcwaSimple::authenticate::request: success.");
                        UcwaSimple.debugResponse(httpResponseOK, "UcwaSimple::authenticate::request");

                        var jsonData: any = httpResponseOK.json();

                        if (jsonData && jsonData._links) {
                            console.log(jsonData);
                            UcwaData.applicationsHref = jsonData._links.applications.href;
                            UcwaData.appDomain = UcwaUtilities.getOriginUrl(jsonData._links.xframe.href);

                            this.createApplication().then(
                                (success) => {
                                    resolve(success)
                                },
                                (error) => {
                                    reject(error)
                                }
                            );
                        } else {
                            reject("Invalid response. Missing WWW-Authenticate header.")
                        }
                    },
                    (httpResponseError: any) => {
                        console.log("UcwaSimple::authenticate::request: error " + httpResponseError.status);

                        httpResponseError.error = "Invalid response " + httpResponseError.status;
                        reject(httpResponseError);
                    },
                    () => {
                        this._isBusy = false;
                    }
                );
            }
        );
```

**Comment by aqib1604** [comment]
Here is response I am getting.

AuthenticationResult {accessToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzUU…2nX9WmRuhHBbJwOmiuSj9aJqRiPmjKCygOVxdxSEfvvdd_RJQ", accessTokenType: undefined, expiresOn: Tue Apr 18 2017 21:18:01 GMT+0530 (IST), idToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiJlYT…X0VyN2JLTDlpRWVGd3dRVXFTa29BQSIsInZlciI6IjEuMCJ9.", isMultipleResourceRefreshToken: false…}
accessToken
:
"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6ImEzUU4wQlpTN3M0bk4tQmRyamJGMFlfTGRNTSIsImtpZCI6ImEzUU4wQlpTN3M0bk4tQmRyamJGMFlfTGRNTSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLndpbmRvd3MubmV0IiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvOTRjNjY2NjEtZjFhMC00ZTFkLTk2YjUtNWMyZmU3YTI1NjI5LyIsImlhdCI6MTQ5MjUyNjU4MiwibmJmIjoxNDkyNTI2NTgyLCJleHAiOjE0OTI1MzA0ODIsImFjciI6IjEiLCJhaW8iOiJZMlpnWUREUTZQUGsyYlRwemFQekZ1ZUVlWHg0M20wdHNyVzZGL2srWDhkaGM0ZDcwdzBBIiwiYW1yIjpbInB3ZCJdLCJhcHBpZCI6ImVhNDJkMGIyLTg2YjQtNGU5Mi04NzE5LTRiNGY2NzY1ZDMxZSIsImFwcGlkYWNyIjoiMCIsImVfZXhwIjoyNjI4MDAsImZhbWlseV9uYW1lIjoib2ZmaWNlIiwiZ2l2ZW5fbmFtZSI6ImRhbnRlbG8iLCJpcGFkZHIiOiIxODAuMjExLjk3LjgxIiwibmFtZSI6IkRhbnRlbG8gT2ZmaWNlIiwib2lkIjoiZWNkYjg5OTEtODQ5ZC00M2UzLWEyNGEtMGVkNGI1MjYwMDVhIiwicGxhdGYiOiIxIiwicHVpZCI6IjEwMDMwMDAwOUU1N0RBNTEiLCJzY3AiOiJEaXJlY3RvcnkuQWNjZXNzQXNVc2VyLkFsbCBEaXJlY3RvcnkuUmVhZC5BbGwgRGlyZWN0b3J5LlJlYWRXcml0ZS5BbGwgR3JvdXAuUmVhZC5BbGwgR3JvdXAuUmVhZFdyaXRlLkFsbCBNZW1iZXIuUmVhZC5IaWRkZW4gVXNlci5SZWFkIFVzZXIuUmVhZC5BbGwgVXNlci5SZWFkQmFzaWMuQWxsIiwic3ViIjoiUmNIcmFwcXJOYmN0ZWxHSl9BRkZGeFFacHNOZGRvc01kcmVyM0tTSWtfdyIsInRpZCI6Ijk0YzY2NjYxLWYxYTAtNGUxZC05NmI1LTVjMmZlN2EyNTYyOSIsInVuaXF1ZV9uYW1lIjoiZGFudGVsby5vZmZpY2VAZGFudGVsby5kayIsInVwbiI6ImRhbnRlbG8ub2ZmaWNlQGRhbnRlbG8uZGsiLCJ1dGkiOiJfRXI3YktMOWlFZUZ3d1FVcVNrb0FBIiwidmVyIjoiMS4wIn0.US7fHV8LEnFcJPUfnedc5D1HsqH2ge6AvMMOYToQ0oXzegX94ha0cVv6fZNv3KevgIwyMm2fNUdE6MJcQGNONLIolu6tfvsqtF7tuI3TAF1ps1mzSEYKAu_rL2wkSYRubXUKQqRJdm2JFVNgnMIVMpvZpO9FOQSKNk9910ETMxvsM7Z20-EJIvRDyexALpyq5ZrFsa580_ULvKUKm4gmktNvis7AcOKIhwz9Ujz83k4C9GBZIr2EnhwfWJk7XNg820otutWumBcpet4Vl56ycUr8cHobBhQzpPEr-2nX9WmRuhHBbJwOmiuSj9aJqRiPmjKCygOVxdxSEfvvdd_RJQ"
accessTokenType
:
undefined
expiresOn
:
Tue Apr 18 2017 21:18:01 GMT+0530 (IST)
idToken
:
"eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiJlYTQyZDBiMi04NmI0LTRlOTItODcxOS00YjRmNjc2NWQzMWUiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC85NGM2NjY2MS1mMWEwLTRlMWQtOTZiNS01YzJmZTdhMjU2MjkvIiwiaWF0IjoxNDkyNTI2NTgyLCJuYmYiOjE0OTI1MjY1ODIsImV4cCI6MTQ5MjUzMDQ4MiwiYW1yIjpbInB3ZCJdLCJmYW1pbHlfbmFtZSI6Im9mZmljZSIsImdpdmVuX25hbWUiOiJkYW50ZWxvIiwiaXBhZGRyIjoiMTgwLjIxMS45Ny44MSIsIm5hbWUiOiJEYW50ZWxvIE9mZmljZSIsIm9pZCI6ImVjZGI4OTkxLTg0OWQtNDNlMy1hMjRhLTBlZDRiNTI2MDA1YSIsInBsYXRmIjoiMSIsInN1YiI6IlpXc3lId1pGbE5wNlI1ZmxINE1kbDEtdzV1WFpkR2Jiem55cV9TSHFpZnciLCJ0aWQiOiI5NGM2NjY2MS1mMWEwLTRlMWQtOTZiNS01YzJmZTdhMjU2MjkiLCJ1bmlxdWVfbmFtZSI6ImRhbnRlbG8ub2ZmaWNlQGRhbnRlbG8uZGsiLCJ1cG4iOiJkYW50ZWxvLm9mZmljZUBkYW50ZWxvLmRrIiwidXRpIjoiX0VyN2JLTDlpRWVGd3dRVXFTa29BQSIsInZlciI6IjEuMCJ9."
isMultipleResourceRefreshToken
:
false
status
:
undefined
statusCode
:
"Succeeded"
tenantId
:
"tenantId"
userInfo
:
UserInfo

**Comment by aqib1604** [comment]
I am referring https://msdn.microsoft.com/en-us/skype/ucwa/authenticationusingazuread link and got stuck on "Resending an autodiscovery request with the bearer token" part. When I provide Above access token with "Bearer ", I am getting "403 - Forbidden: Access is denied."

**Comment by matrosov-nikita** [comment]
Hi @aqib1604, thanks for reporting. Could you please answer on some questions?
Does `accessTokenType` present for silent token acquisition?
Do you have any item in your token cache? If yes, try to clean up a cache first.

As for sending request with token, it seems to me that you missed some headers: 
`X-Ms-Origin: http://app.yourdomain.com`
`X-Requested-With: XMLHttpRequest`

**Comment by aqib1604** [comment]
@matrosov-nikita No Its undefined in silent token acquisition too.

I dont have any item in token Cache.

**Comment by aqib1604** [comment]
@matrosov-nikita One more thing, I found out when I run https://login.microsoftonline.com/common/oauth2/authorize URL after the authentication with ADAL its giving me a Bearer token but I am using his for ionic application, So as a redirect URL I have to use default redirect URL https://login.microsoftonline.com/common/oauth2/nativeclient . Now, when i check the Network from developer console. There is an access token in Location header, But I cant get that access token as its redirecting to https://login.microsoftonline.com/common/oauth2/nativeclient . Is there anyway to get that?

**Comment by matrosov-nikita** [comment]
@aqib1604, sorry for late reply, I'm not sure I understand what you mean. It seems to me that this issue is related to server-side permissions. Could you please check it out again?
Also, as far as I know, `https://login.microsoftonline.com/{tenant}/oauth2/authorize` is using to request authorization code rather than access token (https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code).

**Comment by matrosov-nikita** [comment]
@aqib1604, just a friendly ping, are you still experiencing this problem?

**Comment by matrosov-nikita** [comment]
@vladimir-kotikov, can we close it due to lack of response?

**Comment by vladimir-kotikov** [comment]
Closing this due to lack of response. @aqib1604, if you're still experiencing this, feel free to reopen.

Thanks

**Comment by nabeelzaheer94** [comment]
Can you please tell me code for it ? Actually I am new to ionic, and I am confused what to do. I want to authenticate user by Azure Active directory user. Please help me!
