### ISSUE TITLE
Ionic Custom Login Page With Microsoft Azure Active Directory Protect UI Router Routes

### ISSUE THREAD

**Issue by jcabrera17** [AzureAD/azure-activedirectory-library-for-cordova#144]
### Issue Description
I am using the latest Ionic Framework and have install azure active directory library for cordova. In my app.js file in the .run() function I have the code to authenticate the user when the app is open. It runs and the user is prompt to Microsoft login page. The user logs-in and is redirected to the main view of the app. That works great and the user info is store in the cache and the user is still login. When the user clicks the log out button it redirects them to the Microsoft logout out page and they are logout and I also cleared the token cache and device cache as well. The problem is when the user signs out and click the back button on the mobile device it takes them to the app main page of the ui-router. Then redirects them to the Microsoft login page then when clicking the back button on the mobile device again in takes them to the view and gives a console.log error of Failed to authenticate: Error: User cancelled the flow RequestId:500241452 CorrelationId: b0831ae6-ed73-4949-97a1-fa8c2a965299. Is there away that the user can't view the routes unless they are login and is constantly checking? 

**app.js**
```
$ionicPlatform.ready(function() {
       function authenticate(authCompletedCallback, errorCallback) {
              var authContext = new Microsoft.ADAL.AuthenticationContext(authority);
              authContext.tokenCache.readItems().then(function(catchItems) {
                     if (catchItems.length > 0) {
                            authority = catchItems[0].authority;
                            authContext = new Microsoft.ADAL.AuthenticationContext(authority);
			}
                     // Attempt to authorize user silently
                     authContext
                            .acquireTokenSilentAsync(resourceUri, appId).then(authCompletedCallback, function() { 
                     authContext
                            .acquireTokenAsync(resourceUri, appId, redirectUri)
                                   .then(authCompletedCallback, errorCallback);
                            });
              });
       }
       
       authenticate(function(authResponse) {
              $rootScope.$broadcast('received-user-token', authResponse);
              console.log("Token acquired: " + authResponse.accessToken);
              console.log("Token will expire on: " + authResponse.expiresOn);
       }, function(err) {
              console.log("Failed to authenticate: " + err);
       });
});
```
### Repro Environment Details
1. latest version azure active directory library for cordova
2. Android 5.1.1
3. Nexus 7 Tablet

**Comment by matrosov-nikita** [comment]
@jcabrera17, thanks for reporting, I'm not sure I understand your case, but may be you need to call authentication process again in case of auth error:
```
authContext
    .acquireTokenSilentAsync(RESOURCE_URL, APP_ID).then(authCompletedCallback, function () {
        authContext
            .acquireTokenAsync(RESOURCE_URL, APP_ID, REDIRECT_URL)
            .then(authCompletedCallback, function (err) {
                errorCallback(err);
                authenticate(authCompletedCallback, errorCallback);
            });
    });
```

**Comment by jcabrera17** [comment]
It works!! Thank you :)

**Comment by matrosov-nikita** [comment]
@jcabrera17, thanks for verification!
@vladimir-kotikov, can we close this issue?
