### ISSUE TITLE
Does not work with Visual Studio 2015 Cordova tools.

### ISSUE THREAD

**Issue by takrim** [AzureAD/azure-activedirectory-library-for-cordova#15]
Gives below error

cmd: Command failed with exit code 1

ERROR building one of the platforms	

If I remove this plugin application builds with no error. So clearly this plugin is causing this issue.

**Comment by stevenlivz** [comment]
I also get an error when using the VS2015 command line - fine with 2013 tools. Details below.

c:\dev\code\openglasgow.samples.api.connector.cordova>cordova build windows
Running command: cmd "/s /c "c:\dev\code\openglasgow.samples.api.connector.cordova\platforms\windows\cordova\build.bat""
MSBuildToolsPath: C:\Program Files (x86)\MSBuild\14.0\bin\amd64\
Building project: c:\dev\code\openglasgow.samples.api.connector.cordova\platforms\windows\CordovaApp.Windows.jsproj
        Configuration : debug
        Platform      : anycpu
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1736,5): error APPX0502: File 'C:\Program Files %28x86%29\Windows Kits\10\\Include\WinRT\AppxManifestSchema2010_v2.xsd' not found. [c:\dev\code\openglasgow.samples.api.connector
.cordova\platforms\windows\CordovaApp.Windows.jsproj]
ERROR: Error code 1 for command: C:\Program Files (x86)\MSBuild\14.0\bin\amd64\msbuild with args: c:\dev\code\openglasgow.samples.api.connector.cordova\platforms\windows\CordovaApp.Windows.jsproj,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configuration=debu
g,/p:Platform=anycpu
ERROR building one of the platforms: Error: cmd: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 2
    at ChildProcess.whenDone (C:\Users\start_000\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:134:23)

**Comment by dwheelerjr** [comment]
This still seems to be a bug. I am having the same issue in VS 2015. If I remove ADAL no error. Anyone find a work around or is there a fix somewhere yet?

**Comment by sgrebnov** [comment]
I've just tried to build blank app (created using Tools for Apache Cordova (Update6) from VS 2015 Update1) with ADAL plugin and it seems to work.

Could you please 
0. Specify cordova version used by the app
 *  `cordova --version && cordova platforms` (if you build command line)
 *  VS settings if you build from Visual Studio
![image](https://cloud.githubusercontent.com/assets/981580/13003535/28413da0-d187-11e5-8dde-257e39dd8933.png)
  
1. Whether it does not work when compiling from VS (as looks like you are using command line)
2. Specify VSCordovaTools version you are using
3. Full trace 
  * `cordova build windows --verbose` from command line
  * Visuals Studio output (Ctrl+Alt+O) if you build from VS

**Comment by sgrebnov** [comment]
Closing as this issue does not have enough details, feel free to re-open with more information if this is still actual.
