### ISSUE TITLE
Azure AD Authentication Error: User Cancelled the flow

### ISSUE THREAD

**Issue by paragw09ckp** [AzureAD/azure-activedirectory-library-for-cordova#154]
### Issue Description
I am developing a Hybrid Mobile App using **Ionic 2 and AngularJS 2** framework. And I am trying to develop user authentication functionality using **Azure AD** and having some issue in the process. I have implemented the client-flow authentication using ADAL library but when I try to login it is giving an error as below:

```
Error: User cancelled the flow RequestId:934620772 CorrelationId: 57a1ffe8-7612-49c4-b22d-2704eff74010
at fail (file:///android_asset/www/plugins/cordova-plugin-ms-adal/www/CordovaBridge.js:37:25)
at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:295:52)
at <anonymous>:1:9(anonymous function) @ main.js:121821_rejected @ utility.js:286Deferred.reject @ utility.js:368(anonymous function) @ AuthenticationContext.js:91_rejected @ utility.js:286Deferred.reject @ utility.js:368fail @ CordovaBridge.js:41cordova.callbackFromNative @ cordova.js:295(anonymous function) @ VM298:1
```

The latest **CorrelationId** is **92bb1c8e-9796-462e-8202-6b9a317b95a9**. And the latest error date and time is:

- **Date: 05/24/2017**
- **Time: 03:27:19 PM EST**

Installed ADAL library as below:

`ionic plugin add cordova-plugin-ms-adal@latest`

The way it is implemented is that the user enters his/her email address and taps on “Login” button on the UI. The AngularJS code is:

```
loginWithADAL(userCredentials: any) {
    if (userCredentials.email === null) {
        return Observable.throw("Please insert credentials");
    }
    else {
        return Observable.create(observer => {
            this.authenticate(function (data) {
                console.log('**********AuthService: in loginWithADAL(), data = ', data);
                this.isAuthenticated = true;
                observer.next(true);
                observer.complete();
            });
        });
    }        
}
```

```
authenticate(authCompletedCallback) {
    this.platform.ready().then(() => {
        let authContext = new Microsoft.ADAL.AuthenticationContext(this.adal.authority);
        authContext.tokenCache.readItems().then(
            (items) => {
                if (items.length > 0) {
                    this.adal.authority = items[0].authority;
                    authContext = new Microsoft.ADAL.AuthenticationContext(this.adal.authority);
                }
 
                // Attempt to authorize user silently
                authContext.acquireTokenSilentAsync(this.adal.resourceUri, this.adal.clientId, this.testUser.email).then(
                    authCompletedCallback, 
                    (p) => {
                        // We require user cridentials so triggers authentication dialog
                        authContext.acquireTokenAsync(this.adal.resourceUri, this.adal.clientId, this.adal.redirectUri, this.testUser.email).then(
                            authCompletedCallback, 
                            (err) => {
                                console.error('**********AuthService: in authenticate(), Failed to authenticate via ADAL: ', err);
                                alert("AuthService: Failed to authenticate: " + err);
                            }
                        );
                    }
                );
            },
            (err) => {
                console.error('ERROR: ' + err);
            }
        );
    });
}

```

As expected and as mentioned in various forums/docs, a new login page is launched and displayed where the user enters their password and taps on “**Sign-in**” button. **This is when I am getting the above mentioned error.**

### Repro Environment Details
1. Installed plugin version:  (Have you tried installing the latest plugin version to ensure this has not already  been fixed?) **0.10.0**
2. Target Platform: for example, `Android` or `Windows 10` or `Windows Phone 8.1` **Android**
3. Test device and OS version: for example, `Nexus 5 Android 6.0`, `Windows Mobile 10 emulator`, `Windows 8.1 Desktop x64` 

- **Phone Brand: Motorola**
- **Model: Moto E (2nd Generation)**
- **Android Version: 5.1**

**I have also tried it on ASUS Android tablet and got the same error.**

4. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version? **Command Line**
3. If Windows related, please specify whether SSO option is enabled or not.

**Comment by matrosov-nikita** [comment]
Hi @paragw09ckp, thanks for reporting. I was able to create Ionic2 application with similar behavior (enter login and make token acquisition). But after token request, I got authentication result. This is my code:

home.html
```
<ion-content class="home" padding>
  <form (ngSubmit)="logForm()">
      <ion-item>
          <ion-input type="text" [(ngModel)]="user.email" placeholder="Enter you login..." name="email"></ion-input>
      </ion-item>
       <button ion-button type="submit" block>Run auth</button>
  </form>
</ion-content>
```

home.ts
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

declare var Microsoft: any;

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

export class HomePage {

  user = {
    email: ''
  }

  adal = {
    resourceUri: "https://graph.windows.net/",
    clientId: '<appId>',
    redirectUri: '<redirectUri>',
    authority: '<authorityUrl>'
  }

  constructor(public navCtrl: NavController) { }

  logForm() {
    // set log level with code=3 (verbose level)
    Microsoft.ADAL.AuthenticationSettings.setLogLevel(3).then(() => {
      console.log("Successfully set log level");
      Microsoft.ADAL.AuthenticationSettings.setLogger(function (logItem) {
        console.log(JSON.stringify(logItem, null, 2));
      });
    }, (err) => {
      console.log("Couldn't set log level");
    })


    this.authenticate(function (res) {
      console.log(res);
    });
  }

  authenticate(authCompletedCallback) {
    let authContext = new Microsoft.ADAL.AuthenticationContext(this.adal.authority);
    authContext.tokenCache.clear();
    authContext.tokenCache.readItems().then(
      (items) => {
        if (items.length > 0) {
          this.adal.authority = items[0].authority;
          authContext = new Microsoft.ADAL.AuthenticationContext(this.adal.authority);
        }

        // Attempt to authorize user silently
        authContext.acquireTokenSilentAsync(this.adal.resourceUri, this.adal.clientId, this.user.email).then(
          authCompletedCallback,
          (p) => {
            // We require user cridentials so triggers authentication dialog
            authContext.acquireTokenAsync(this.adal.resourceUri, this.adal.clientId, this.adal.redirectUri, this.user.email).then(
              authCompletedCallback,
              (err) => {
                console.error('**********AuthService: in authenticate(), Failed to authenticate via ADAL: ', err);
                alert("AuthService: Failed to authenticate: " + err);
              }
            );
          }
        );
      },
      (err) => {
        console.error('ERROR: ' + err);
      }
    );
  }
}
```

My ionic settings (could you please post here your settings using `ionic info` command):
```
global packages:

    @ionic/cli-utils : 1.2.0
    Cordova CLI      : 7.0.2
    Ionic CLI        : 3.2.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.2.1
    @ionic/cli-plugin-ionic-angular : 1.2.0
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.4.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
```
Since v0.10.0 we've added logger implementation for consuming internal logs from native libraries.
Are you able to set logger in your application using the following snippet (also see [docs](https://github.com/AzureAD/azure-activedirectory-library-for-cordova#logging)):
```
    // set log level with code=3 (verbose level)
    Microsoft.ADAL.AuthenticationSettings.setLogLevel(3).then(() => {
      console.log("Successfully set log level");
      Microsoft.ADAL.AuthenticationSettings.setLogger(function (logItem) {
        console.log(JSON.stringify(logItem, null, 2));
      });
    }, (err) => {
      console.log("Couldn't set log level");
    })
```
and post your logs here?

Also, just for your information, there were some issues (https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/111, https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/145) related to Android Webview. Not sure, that it's your case, but you can try to upgrade your `Android System Webview`.

**Comment by paragw09ckp** [comment]
Hi Nikita,

Thanks for looking into this and making it work at your end. I will try it in some time and get back to you.

On the first glance, I don’t see any difference between my code and yours except for two things:


1.       For “resourceUri” you are using “https://graph.windows.net/” and I am using “https://login.windows.net/common” as per the docs.

2.       Logger implementation that was added with v0.10.0.

I will make these changes and try again. Will get back to you with my results.

Thanks again for your much needed help, appreciated!


Best Regards,
Parag Wargantiwar

**Comment by paragw09ckp** [comment]
Hi Nikita,

I tried it on my end but it is still not working. And this time it just stays on my login page. Does not open the Microsoft login page where I would enter my AD password. I am guessing it’s because I am using “resourceUri” you used (https://graph.windows.net/).

The other change you had in your code is that you are clearing tokenCache (authContext.tokenCache.clear()) in authenticate function. I added that as well.

Also added the v.0.10.0 logger and enabled it, must be enabled as I am getting the log “Successfully set log level”.  How do I get the logs created from logger than you have added with v0.10.0?


I am debugging/inspecting the app that is running on phone in my laptop browser by using this: chrome://inspect/#devices
All the logs are printed in developer console there.

The error I see is as below:
[cid:image001.png@01D2D548.E15C7460]

My “ionic info” is as below:
$ ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.0.0
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.3.7
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.9.4
Xcode version: Not installed

Ionic 3.0 is not finalized yet so we are not upgrading to it yet. Our app will be based on Ionic 2.

Finally, regarding the issues you mentioned (#111<https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/111>, #145<https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/145>), I did not face those issues yet. However, I checked on the phone I am using for my testing, the Android System WebView version is 58.0.3029.83 and I don’t get any option to upgrade it further. In fact, there is an option to Uninstall Updates” so I am assuming it’s up-to-date.


Best Regards,
Parag Wargantiwar
Checkpoint Systems, Inc.
Work:    +1 856 251 2181
Cell:       +1 732 447 8800
E-mail:    Wargantiwar.Parag@checkpt.com

**Comment by paragw09ckp** [comment]
Hi again Nikita,

I notice one thing just now.

You are using Graph API URI for "**resourceUri**" value. When I tried it on my end, I actually changed "**authority**" value thinking in my head that rest of the variables () are for specifying values related to my app. And I posted it's working. Clearly, that won't work.

**My apologies.**

This time changed the correct variable's value (i.e. "resourceUri"). And it seems to work fine. I mean, if everything works as it is supposed to then upon successful login it should land me on my app's home page. But it is coming back to my login page. Maybe it's related to the issues (#111 and #145 ) you mentioned in your first reply. I will go through them in more details to confirm.

So the right way to assign "**resourceUri**" value is the URI of the Graph API and not one's app service. I was following the below link for my development and used my app service's URI.

https://shellmonger.com/2016/04/06/30-days-of-zumo-v2-azure-mobile-apps-day-4-adal-integration/
Here is the screenshot on the above link where it talks about “resourceUri”:
![auth](https://cloud.githubusercontent.com/assets/17579929/26461153/2395dbc4-414a-11e7-9a95-f28fdc340ca4.PNG)

Maybe, things changed from the time the link was created.

Thanks again for your great and timely help, appreciated!!

**Comment by matrosov-nikita** [comment]
@paragw09ckp, thanks for the verification.
I guess, you need to remove this line `authContext.tokenCache.clear();` (I've added it just for testing purposes), otherwise, the non-silent token acquisition will be failed before each attempt to authorize due to empty cache and you will be returned back to the login page.

**Comment by matrosov-nikita** [comment]
@vladimir-kotikov, can we close it due to lack of response?

**Comment by vladimir-kotikov** [comment]
Closing. @paragw09ckp, feel free to reopen if you have any issues
