### ISSUE TITLE
ios: Existing Entitlements File replaced with new one

### ISSUE THREAD

**Issue by FBNitro** [AzureAD/azure-activedirectory-library-for-cordova#156]
### Issue Description
My app currently has an entitlements file, referenced by the XCode project.  After going through the cordova plugin add, the entitlements file reference in the xcode project is changed to be the ADALiOS.entitlements file.  My existing entitlements are no longer applied, and the app stops working correctly (for push in my case).

If possible, it should merge the entitlements into the existing entitlements file if one is already referenced in the xcode project, instead of assuming this entitlements file is correct.

### Repro Environment Details
1. Installed plugin version:  0.9.0
2. Target Platform: iOS
3. Test device and OS version:  10+
4. Cordova command line.

**Comment by matrosov-nikita** [comment]
Hi @FBNitro, thanks for reporting, I'll take a look at this issue.

**Comment by matrosov-nikita** [comment]
@FBNitro, I've tried to reproduce this issue w/o any luck, values from `ADALiOS.entitlements ` are successfully merged in `Entitlements-Debug.plist` and existing values remain in this file (w/ both 0.9.0 and 0.10.0 versions).

Could you please specify the name of your entitlements file?

**Comment by FBNitro** [comment]
My Entitlements file is named after the app.   <appName>.entitlements

**Comment by matrosov-nikita** [comment]
@FBNitro, let us know once you upgrade your environment.

**Comment by FBNitro** [comment]
Looks ok after the upgrade.  I went up to 4.3.0 w/cordova 6.5.0 CLI, I had to use the new Entitlements-Debug/Release.plist instead of my <appName>.entitlements, but all is well.  Thanks.  Closing this issue.
