### ISSUE TITLE
.NETCore,Version=v4.5.1 not found when building with VS 2017

### ISSUE THREAD

**Issue by filionf** [AzureAD/azure-activedirectory-library-for-cordova#157]
### Issue Description
I am unable to add the plugin to a cordova project using Visual Studio 2017. 
`error MSB3644: The reference assemblies for framework ".NETCore,Version=v4.5.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed.`

### Repro Environment Details
1. Create a new Cordova project using the Visual Studio template
2. Using the config.xml, change the options to build for Windows 10 and add the ADAL for Cordova plugin.
3. Build

I am wondering if that is an environment problem I am having and if that can be reproduced by someone else? I have not found where I could download .NETCore v4.5.1, but I did re-installed .NET 4.5.1.

**Comment by vladimir-kotikov** [comment]
@filionf thanks for reporting! @matrosov-nikita, couldyou please take a look?

**Comment by matrosov-nikita** [comment]
I confirm this bug and going to take a deeper look at it.

**Comment by matrosov-nikita** [comment]
@filionf, I made PR, could you please test it and let us know whether it resolves build problem in VS2017.
@vladimir-kotikov, can you review?
I'm also going to test this fix with VS2015 to check back compatibility.

**Comment by filionf** [comment]
Yes, I confirm it works with VS2017. Thanks @matrosov-nikita .

**Comment by matrosov-nikita** [comment]
It works with VS2015 as well.

**Comment by vladimir-kotikov** [comment]
Closed via #158
