### ISSUE TITLE
VS2015 Codova tool build failed in iOS device when adding ADAL plugin

### ISSUE THREAD

**Issue by jychunyih** [AzureAD/azure-activedirectory-library-for-cordova#16]
The issue is as below (if you build using emulator, you will only receive a warning)
Error		The file “ADALiOS.entitlements” couldn’t be opened because there is no such file.: (null)	BlankCordovaApp7	c:\users\chunyih\documents\visual studio 2015\Projects\BlankCordovaApp7\BlankCordovaApp7\MDAVSCLI	1

How to fix (work around, need plugin code fix)
Go to the project in Mac and open the remote build project using XCode, go to the build setting and change the entitlement setting from "/MOA/Resources/ADALiOS.entitlements" to "MOA/Resources/ADALiOS.entitlements".

**Comment by mikkk24** [comment]
Working plugin code fix can be done in file scripts/configureEntitlementsIos.js after line 61 adding the following line:

		entitlementsFile = "\"" + entitlementsFile.substring(2);

**Comment by sgrebnov** [comment]
+1, same issue when using Node v0.10.32, Cordova@5.4.0 and cordova-ios@3.9.2; sent PR#23 with the fix
