### ISSUE TITLE
this plugin does not work on Android device. It is stuck on the Azure AD signin page, I am using my Azure AD domain account.

### ISSUE THREAD

**Issue by takrim** [AzureAD/azure-activedirectory-library-for-cordova#18]
![screenshot_2015-08-16-01-00-07](https://cloud.githubusercontent.com/assets/7156178/9292508/4bb7d716-43b2-11e5-9474-9d594a081923.png)

**Comment by stevenlivz** [comment]
I am using it on Android fine with an Azure AD account. Can you put in more detail.

**Comment by takrim** [comment]
Seems like this is issue in cordova 5.1.1 , which is fixed in cordova j5.2.0
