### ISSUE TITLE
Use the VS2013+ Tools to Build

### ISSUE THREAD

**Issue by stevenlivz** [AzureAD/azure-activedirectory-library-for-cordova#19]
More of a heads up than an issue as it cost me some time.

Once you have done "cordova platform add windows" (avoid wp8), if you are in a normal command line it will use VS2012 if you will get MakePri "Schema Validation Failed" and so on .... took me a while to figure this out.

Just open a VS 2013 command prompt (not that it will say 2012 in the path but ignore that).

It should now build properly.

**Comment by sgrebnov** [comment]
Thank you for the tip, closing as no action items are required (I will see we could add this to docs)
