### ISSUE TITLE
No way to find reply URL issued by Windows\Store when using ADFS

### ISSUE THREAD

**Issue by PJHumbug** [AzureAD/azure-activedirectory-library-for-cordova#196]
### Issue Description
When enabling ADFS support using `<preference name="adal-use-corporate-network" value="true" />'` then trying authenticate I see an invalid reply URL message. 

https://i.stack.imgur.com/oJMdM.jpg 

This message doesn't occur when not using "adal-use-corporate-network" but then I cannot authenticate when on company network (only direct with AAD). 

Tracing through the library and checking the logs I can see no errors when the error message is shown. All I can do in UI is close the login window so the library reports that the user cancelled the operation. 

The one in the code is registered in AAD.

My theory is because the app is registered with the store it is changing the reply URL but the is no way for me to find out what it has changed it to!

Tried but not worked:
Checking AAD and ADFS logs in trace but seems to say authentication successful - no errors.
Stepping through code but cannot see reply URL change. 
The instructions for the .NET library say to check in code but that's not possible in Cordova:
https://github.com/Azure-Samples/active-directory-dotnet-native-uwp-wam
On same page it descibes the format of the URL is like this:
ms-appx-web://Microsoft.AAD.BrokerPlugIn/S-1-15-2-2650639956-658609593-457089695-429683492-3460685052-1353383220-3160185542
I tried this URL replacing the code with package id in Store: https://developer.microsoft.com/en-us/dashboard 

### Repro Environment Details
1. Installed plugin version:  0.10.1
2. Target Platform: Windows 10
3. Cordova and platform versions: Cordova 8.0.0. Windows Platform 6.0.0 
4. Test device and OS version: Windows 10 Desktop X64
5. Visual Studio 2017 + TACO. Updated Cordova and plugins via command line.
6. Using ADFS/SSO. App registered to Windows Store as Line of business application. 
7. No reply URL in logs

Stackoverflow question:
https://stackoverflow.com/questions/51309537/how-to-get-allocated-reply-url-when-using-adal-plugin-for-cordova-in-windows-on

**Comment by ramaguduri** [comment]
You can get redirect URL for Windows by executing below function in JS after device ready event,  Windows.Security.Authentication.Web.WebAuthenticationBroker.getCurrentApplicationCallbackUri()

When using <preference name="adal-use-corporate-network" value="true" />, this library hard codes  redirect URL. You can find this in line 180 in this file - https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/src/windows/ADALProxy.js

Hope this helps you!

**Comment by PJHumbug** [comment]
@ramaguduri - thanks I got the redirect URI. Won't be able to test until later this week so will report back result. 

Really appreciate the response.

**Comment by PJHumbug** [comment]
Just to advise that this did work in the end. However if anyone runs into the same issue **be careful that a debug build and and release build results in different redirect URLs so you need to add both to AAD.** 

@ramaguduri - thanks for your help.
