### ISSUE TITLE
Adding Windows native libs without hooks

### ISSUE THREAD

**Issue by ligaz** [AzureAD/azure-activedirectory-library-for-cordova#2]
Is there any particular need to use hooks to manipulate native projects? The functionality used is already available declaratively in the `plugin.xml`.

**Comment by sgrebnov** [comment]
The main issue here is that both Phone and PC/Tablet ADAL native libraries for Windows have the same name so if we use default Cordova API thery are placed to the same folder and overwrite each other. So we temporary use hoojs based approach and looking how to fix this

**Comment by sgrebnov** [comment]
I've reviewed framework installation logic for Windows and there is no such param so closing this

**Comment by sgrebnov** [comment]
`target-dir` support has been added so hooks could be removed in favor of this attribute

**Comment by sgrebnov** [comment]
Added implementation w/o hook: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/74fe14be8ec59af444c56e6c53e384cf47922ea5
