### ISSUE TITLE
How about a logout function?

### ISSUE THREAD

**Issue by DeBiese** [AzureAD/azure-activedirectory-library-for-cordova#21]
The plugin currently provides ways to login, but how about logout? We all use applications on our smartphone, most of those provide a logout functionality, no?

**Comment by sgrebnov** [comment]
I think this could be done using `authContext.tokenCache.clear()`

**Comment by DeBiese** [comment]
I'm sorry for leaving this open for so long. You are absolutely right. Clearing the tokencache will result in the logout.

**Comment by Prince08Lamba** [comment]
authContext.tokenCache.clear() removes token from app side but it stays logged in on azure side

**Comment by myusrn** [comment]
@Prince08Lamba elsewhere I was referred to this adal for cordova readme section [ https://github.com/AzureAD/azure-activedirectory-library-for-cordova#how-to-sign-out ] that contains details of url to call with xhr or inappbrowser in order clear aad sts issued single signon [ sso ] cookie. 

With that cleared users will be prompted form credentials during subsequent oauth signin flows vs it being silent for the lifetime of the sso cookie.

That said my experience has been that end users rarely want thier sso cookie cleared as they rarely have a desire yo reenter their credentials or logon using different credentials. Where that arises more often is as a part of dev/test work where a redeploy/install of app can alternatively be used to clear app storage maintained cookie container populated by app's prior xhr and inappbrowser activity.

**Comment by SPDoctor** [comment]
The ADAL.JS version of the library has an explicit **logout** function. I assume this deletes the token from AAD. 

In practice clearing the tokenCache has the same effect, except that the tokens must surely continue to exist in AAD until they expire. I am sure AAD can cope with very large numbers of tokens and so we can probably live without having an explicit logout method.
