### ISSUE TITLE
How to use Company Active Directory?

### ISSUE THREAD

**Issue by karthikSwaminithan** [AzureAD/azure-activedirectory-library-for-cordova#22]
I am new to Active Directory and we have a requirement that is we need to consume client's active directory in mobile how to move about. Can you please explain the steps to be followed in order to consume active directory in mobile. 

Thanks

**Comment by sgrebnov** [comment]
The following sample and documentation might be useful for you
https://github.com/AzureAD/azure-activedirectory-library-for-cordova
