### ISSUE TITLE
iOS archive cordova-plugin-ms-adal-is-back capacitor

### ISSUE THREAD

**Issue by alantom1423** [AzureAD/azure-activedirectory-library-for-cordova#220]
Hi
Unable to archive the ionic project in Capacitor while using the plugin cordova-plugin-ms-adal-is-back. 
Its throwing error **Undefined symbol: _OBJC_CLASS_$_ADKeychainTokenCache**, **Undefined symbol: _OBJC_CLASS_$_ADAuthenticationContext** **Undefined symbol: _OBJC_CLASS_$_ADLogger**, **Undefined symbol: _OBJC_CLASS_$_ADAuthenticationError**.

I'm able to build in dev environment but while archiving for release the error comes up. I cannot use ionic cordova since the project is already build with ionic capacitor. Kindly help me.

**Comment by naxxum-mchallouf** [comment]
Hi
We are facing the same issue above. Anyone have already fiwed that ?

**Comment by hbouhali** [comment]
Hey @alantom1423 , Have you solved this issue ? we are having the same issue when trying to archive. Also it is a capacitor ionic project. 
Il will be thankful for any help.

**Comment by alantom1423** [comment]
Hi I solved this...Its because ADAL.framework file provided in this repo is not supporting arm64 architecture. We have to compile the framework and replace the current ADAL.framework from this repo with new compiled ones

Steps

1) Download 4.0.7 release from https://github.com/AzureAD/azure-activedirectory-library-for-objc/releases 

2) Download identity core from https://github.com/AzureAD/microsoft-authentication-library-common-for-objc/tree/97d5d5d4786c0aeda07989cda99e0208f8419dcf 

3) Copy identity core files to respective 4.0.7 project folder 

4) Add cordova-plugin-ms-adal-is-back to the ionic project 

5) Copy the build_sdk.sh from *src->ios->tools* folder from this repo https://github.com/AzureAD/azure-activedirectory-library-for-cordova

6) Add the *BITCODE_GENERATION_MODE=bitcode* after xcodebuild in both the lines in the above shell script 

<img width="1203" alt="Screenshot1" src="https://user-images.githubusercontent.com/49264857/96447771-0e257c80-1230-11eb-8567-1d26b3a6a622.png">

7) Copy the shell script in the root folder of ADAL project extracted from 4.0.7 download  in step1

8) Run the *ADAL.xcworkspace* found inside the download from step1 to check if any errors 

9) Run the shell script with the command **sh build_sdk.sh** from terminal. Before running the script change your directory of terminal to the folder where we have copied the *build_sdk.sh* ie the root folder of ADAL project

10) The above script generates bit code enabled ADAL.framework folder which supports 64 bit architecture 

11) Replace the ADAL.framework in the cordova-plugin-adal-is-back folder and clean and build the ionic project. This can be found inside your ionic project in *ios>capacitor-cordova-ios-plugins>sources>CordovaPluginMsAdalIsBack>src>ios*

12) Archive the project to generate ipa files

**Comment by alantom1423** [comment]
Hi newly updated repo
https://github.com/alantom1423/azure-activedirectory-library-for-cordova
