### ISSUE TITLE
implementing the plugin in Ionic

### ISSUE THREAD

**Issue by Cage10** [AzureAD/azure-activedirectory-library-for-cordova#26]
Hello,
I am trying to implement it in the Ionic framework. I can't get it to work - after installation, I get the "Error: Microsoft is not defined". I suppose I have to inject some dependency to the controller, but what exactly?

**Comment by tavikukko** [comment]
Hi, are you running it in browser (ionic serve)? that will not work cos ionic serve will not load cordova.js. Try running it in emulator (eg. ionic emulate ios). Also use $window.Microsoft.ADAL.. If that does not work, wrap the $ionicPlatform.ready(function() { 
// your code here $window.Microsoft...
}; around the function call.

also you can add browser as a platform ionic platform add browser and then use

**Comment by gregor-srdic** [comment]
$ionicPlatform.ready worked for me on this issue, thanks!

**Comment by Cage10** [comment]
It worked, thanks a lot!
Tip for everyone considering using ADAL AngularJS on a mobile app instead - don't. There are a lot of problems on emulator / device, when "http" changes to "file".

**Comment by Balaji-Gopal** [comment]
I am trying to use the same in Ionic 1 but I do get the same error mentioned @Cage10  "Error: Microsoft is not defined"..
If I use $window.Microsoft.ADAL.AuthenticationContext, then I do get the ADAL is undefined.
I even tried wrapping the function inside $ioniPlatform.ready but still I get the same error
How do we use it in Ionic 1?

**Comment by jcabreraBSK** [comment]
Have anyone figure out, how to protect the views in ionic when the user is signed out? When the user is sign-out they can hit the back button on the device and it will still take them to the views of the app without logging in.
