### ISSUE TITLE
Token expiring in less then 30 seconds

### ISSUE THREAD

**Issue by cmicoe** [AzureAD/azure-activedirectory-library-for-cordova#28]
I am using this plugin and successfully created authentication context and acquiring token. But the token is expires in just seconds. How can I get the token which is valid for few hours or minutes.
I am using latest Cordova 5.4.1 version

**Comment by sgrebnov** [comment]
Hey @cmicoe 
* Do you refer to information stored in `authenticationResult.expiresOn` field returned in success promise?
* Which platform is it? Does it work the same on other platforms?

**Comment by cmicoe** [comment]
Hi @sgrebnov ,

Please find the details about the Token Expiry below.

   {
      [functions]: ,
      __proto__: { },
      accessToken: "eyJXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
      accessTokenType: "Bearer",
      expiresOn: [date] Thu Feb 11 2016 17:26:13 GMT+0530 (India Standard Time),
      idToken: "eyJ0XXXXXXXXXXXXXXXXXXXXXXXXXXXX.",
      isMultipleResourceRefreshToken: true,
      status: 0,
      statusCode: 0,
      tenantId: "XXXXXX-3XXX-4XX8-9XX6-XXXXXXXXX",
      userInfo: { }
   }

Token is getting valid for 1 hour but the password in the User Info getting expired immediately after we login. Below is the example

userInfo: {
         [functions]: ,
         __proto__: { },
         displayableId: "COE DATA",
         familyName: "ADMIN",
         givenName: "COE",
         identityProvider: "https://sts.windows.net/dXXXXf08-3XXd-4XX8-9XX6-7XXXXXXXXX4/",
         passwordChangeUrl: undefined,
         passwordExpiresOn: "Thu Feb 11 2016 16:26:14 GMT+0530 (India Standard Time)",
         uniqueId: "uday@XXXXXXXsoftware.onmicrosoft.com",
         userId: "f6XXX1d3-eXX6-4XXb-XXXX-7XXXXXXX592"
      }

**Comment by sgrebnov** [comment]
Similar situation is explained here
https://azure.microsoft.com/en-us/documentation/articles/active-directory-devquickstarts-cordova/#comment-2444775114

> The password expiration is a server only concern - and should not impact the token handling at all. Either you get a token or you don't - and in case you do get a token, the password expiration should only be a warning in the returned results in case the expiration date is imminent. Can you explain exactly what you are observing? Also, what happens if you use the same user credentials in a different application?

**Comment by sgrebnov** [comment]
Does received token continue to work after that? Could you please explain real impact on the app.

**Comment by cmicoe** [comment]
Well we are capturing two tokens one using adal-angular.js for webAPI and ADAL Plugin for mobile clients.

Token obtained for WEBAPI through ADAL-ANGULAR.JS is working as expected and getting validated for authorization where as the token obtained using CORDOVA ADAL Plugin for windows is not getting validated for further authentication. Shared Token details are from CORDOVA ADAL Plugin.

**Comment by sgrebnov** [comment]
Looks like I found the problem
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/www/UserInfo.js#L58
```
result.passwordExpiresOn = token.exp ? Date(token.exp) : null;
```
Actually it should be (code above returns current time)
```
result.passwordExpiresOn = token.exp ? new Date(token.exp) : null;
```

**Comment by sgrebnov** [comment]
But it does not answer the question why token obtained using Cordova is not getting validated for further authentication.
