### ISSUE TITLE
Weird authflow issue on sample

### ISSUE THREAD

**Issue by jsiegmund** [AzureAD/azure-activedirectory-library-for-cordova#29]
I've built the sample (https://github.com/Azure-Samples/active-directory-cordova-multitarget) and tried it. When I perform a search, the login windows pops up. I choose "login with a Microsoft account" because I'm using my Microsoft account for Azure. The other login screen appears and I enter my credentials, after which it asks for the verification code on my phone. Now after what I believe to be a successful login, I'm returned to the corporate login screen again. I can choose "Microsoft account" again and the whole process endlessly repeats. 

I'm lost in why this happens as there is so little to go on, I don't see any error messages. Any idea?

**Comment by sgrebnov** [comment]
Hey @jsiegmund which platform is it?

**Comment by jsiegmund** [comment]
Hi @sgrebnov. I'm sorry as I lost track of this one. It can be closed, it was my own mistake. I found out that instead of using the "web application" type application in Azure AD (as I thought was right because this is html / javascript and all), you need to choose "native" instead. I guess since Cordova compiles things to native code which then runs on the phone it does make sense.

The above would cause the authentication process to fail and my code would then immediately retry, causing the endless loop of pop-ups. More info @ http://stackoverflow.com/questions/35078656/cordova-app-using-angular-adal

**Comment by sgrebnov** [comment]
Great to hear you've solved your problem, we will see how to improve documentation to highlight this.
