### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by Borja204** [AzureAD/azure-activedirectory-library-for-cordova#3]
Error	3	El comando ""C:\Users\borja.alvarez.ELNR\AppData\Roaming\npm\node_modules\vs-mda\vs-cli" build --platform "Android" --configuration "Debug" --projectDir . --projectName "BlankCordovaApp1" --language "es-ES" --buildServerUrl "" --buildTarget "AndroidDevice"" salió con el código 8.	C:\Users\borja.alvarez.ELNR\AppData\Roaming\npm\node_modules\vs-mda-targets\Microsoft.MDA.targets	99	5	BlankCordovaApp1
Error	2	H:\HYBRID\BlankCordovaApp1\BlankCordovaApp1\bld\Debug\platforms\android\cordova\build.bat: Command failed with exit code 2	H:\HYBRID\BlankCordovaApp1\BlankCordovaApp1\EXEC	1	1	BlankCordovaApp1

When i add plugin to project it makes the build fail, ihavent found any solution, any idea?

**Comment by EivindJacobsen** [comment]
I have similiar issue. I open new cordova project in visual studio 2013. Then i open config and add azure-activedirectory-library-for-cordova plugin. Then when I try to build, it fails. It just says "Uh, Oh!" in the output.

**Comment by sgrebnov** [comment]
This is fixed now as we added Ant support which is used by VS
