### ISSUE TITLE
Issue mapping displayName from context on Windows Phone 8.1

### ISSUE THREAD

**Issue by GaryMcAllister** [AzureAD/azure-activedirectory-library-for-cordova#30]
The line below in the ADALProxy returns a WinJS error causing a failure.

displayName = mapUserUniqueIdToDisplayName(context, userId);

I am writing a Windows Universal Phone App on Windows Phone 8.1 Update 2.

WinRTError: No such interface supported

System.InvalidCastException: Specified cast is not valid.
   at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
   at mapUserUniqueIdToDisplayName

**Comment by Vital-k** [comment]
any update on this one? :) got the same on windows emulator

**Comment by sgrebnov** [comment]
I plan to take a look on this today! Will keep you updated

**Comment by Vital-k** [comment]
super! thanks!

**Comment by sgrebnov** [comment]
Could be related issue: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/14#issuecomment-158230254

**Comment by sgrebnov** [comment]
I can see this when I target `arm` architecture and everything works correct when I run app as `anycpu` on the same deive
```
System.InvalidCastException: Specified cast is not valid.
   at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
WinRT information: System.InvalidCastException: Specified cast is not valid.
   at System.StubHelpers.InterfaceMarshaler.ConvertToNative(Object objSrc, IntPtr itfMT, IntPtr classMT, Int32 flags)
The program '[80] WWAHOST.EXE' has exited with code -1 (0xffffffff).

```

**Comment by sgrebnov** [comment]
@GaryMcAllister , could you please specify whether you are using VSCordovaTools to run the app or command line...

**Comment by GaryMcAllister** [comment]
Cordova Tools but the error is experienced once deployed.

I commented the line out and all was well (I hope). :-S

**Comment by sgrebnov** [comment]
VS2015 Cordova Tools automatically build and run app under `arm` when deploying to WP 8.1 device.

In a mean time as possible workaround you can try the following (while I'm working on general fix, as it could take some time): 

1. Use emulator
2. Open generated `windows` project (<your app>\platforms\windows\CordovaApp.sln), select Windows Phone 8.1 project as start up and run on device under anycpu
![image](https://cloud.githubusercontent.com/assets/981580/13008544/f597691c-d1a7-11e5-9737-35afe662be7e.png)


![image](https://cloud.githubusercontent.com/assets/981580/13008559/fff03dbc-d1a7-11e5-912e-01db0648b415.png)
3. Use command line (from cordova project root)
```
 cordova run windows --device -- --phone
```

**Comment by sgrebnov** [comment]
PS. Great you have another workaround (commenting line(s) ) as well. :)

**Comment by GaryMcAllister** [comment]
Great! Thanks :-)

**Comment by Vital-k** [comment]
commenting line doesn't help in my case... just silent break in another place...

**Comment by Vital-k** [comment]
Any news on when it is could be solve? we would like to release our app next week :-) will be really nice if we can do it for windows phone as well :)

**Comment by sgrebnov** [comment]
Hi @Vital-k, I'm working on this but looks like it is tricky issue related to ADAL native library (just tried the latest version and see the same issue) and msbuild14, another person has already looked on this some time ago (https://github.com/AzureAD/azure-activedirectory-library-for-cordova/compare/master...daserge:arm-fix?expand=1).

Temporary workarounds suggested 
1)	An app could be either built in AnyCpu mode (which will not apparently work if there are any C++ libs, for example cordova-SQLite-storage plugin), 
2)	Or it should be built in VS 2013 (msbuild12).

For release purpose -can you give instructions above a try and let me know if they work?
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/30#issuecomment-183336814

**Comment by sgrebnov** [comment]
I found out that if I change the following ADAL lib file to return Array instead of List, then the code works fine.

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.Common/TokenCache.cs#L217

**Comment by sgrebnov** [comment]
Looks like the issue is similar to what is described here, the same workaround creating a new type for `IEnumerable` work. Since it does not change public api signature, I'll re-compile the lib using this approach, run auto-tests and update code (if tests pass).

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/16fa4316-d0ae-4aca-ac70-9946c6cc4dfb/ngend-dll-throws-exception-but-winmd-does-not?forum=wpdevelop

**Comment by GaryMcAllister** [comment]
Thanks Sergey!

Well done :-)
