### ISSUE TITLE
Issue signing in with Personal Account

### ISSUE THREAD

**Issue by Dismissile** [AzureAD/azure-activedirectory-library-for-cordova#31]
I have an Azure Tenant set up from my MSDN account which is name@company.com
My tenant was created automatically when I signed up for my Azure benefits as namecompany.onmicrosoft.com

- I also have an Office 365 account (Org ID) with the same email as my Personal account.
- When I run the default sample it will redirect me to the microsoft login.
- I type my email and focus to the password field. 
- At this point I get the standard "is this an Org ID or Personal account. 
- I choose Personal account since my personal account is what I use to log into the Azure Management portal. 
- It redirects me to the login for personal accounts.
- I type my password and successfully authenticate.
- It redirects me back to my native app and the authResult from the promise has null for accessToken and userInfo objects.

I can successfully login and get a token if I use a new user that I create on the tenant foobar@namecompany.onmicrosoft.com

The authResult for the response looks like:
{"expiresOn": null, "isMultipleResourceRefreshToken": false, "statusCode": "Failed", "userInfo": null }

This is hitting the success handler in promise.

**Comment by sgrebnov** [comment]
Hi @Dismissile, on which cordova platform do you see this?

**Comment by Dismissile** [comment]
Hi @sgrebnov. I believe I have found out why this wasn't working. Based on the following SO post: http://stackoverflow.com/questions/35064827/azure-ad-authentication-issue-in-cordova-plugin I was able to determine that the problem was trying to use a Live ID with the /common endpoint.

**Comment by sgrebnov** [comment]
Thank you for the details, I'm closing this issue then
