### ISSUE TITLE
is this repo the source for cordova-plugin-ms-adal

### ISSUE THREAD

**Issue by myusrn** [AzureAD/azure-activedirectory-library-for-cordova#32]
in the https://github.com/Azure-Samples/active-directory-cordova-multitarget sample it outlines using this repo, i.e. 
git clone https://github.com/AzureAD/azure-activedirectory-library-for-cordova.git [d:\src\repos\]azure-activedirectory-library-for-cordova, as source for enabling adal cordova plugin in vs15upd1 cordovaUpd5, aka taco, project environment.

I'm finding that when i visit vs15upd1 cordovaUpd5, aka taco, project environment config.xml | plugins there is now an "adal for cordova [ / cordova-plugin-msadal ]" entry that comes from https://www.npmjs.com/package/cordova-plugin-ms-adal.

is this git repo the source for that published cordova plugin offering or are they separate efforts and if so which one is the supported story i should be using?

**Comment by sgrebnov** [comment]
Confirm this. Please note, you may have slightly different code as we could add more changes to the repository after npm release
