### ISSUE TITLE
Cordova ADAL Azure AD acquireTokenAsync fails with certificate error

### ISSUE THREAD

**Issue by arthuryegiazaryan** [AzureAD/azure-activedirectory-library-for-cordova#36]
I'm getting a certificate error which I outlined in [this stackoverflow article](http://stackoverflow.com/questions/35323960/cordova-adal-azure-ad-acquiretokenasync-fails-with-certificate-error).  Can the git community please help me figure this out?

**Comment by sgrebnov** [comment]
Vittorio  replied on stackoverflow, waiting for response
http://stackoverflow.com/a/35348215/255654

**Comment by sgrebnov** [comment]
Looks like the problem is not actual anymore (as per StackOverflow), closing...
