### ISSUE TITLE
Permissions needed for broker?

### ISSUE THREAD

**Issue by joshgav** [AzureAD/azure-activedirectory-library-for-cordova#4]
Found the following in LogCat when authenticating. 

`607-19355/com.microsoft.services.sample.cordovaApp W/BrokerProxy﹕ DEVELOPER_BROKER_PERMISSIONS_MISSING:2015-04-28 04:52:22-b45b17ac-6b97-4901-a360-a30222614f6d-Broker related permissions are missing for GET_ACCOUNTS, MANAGE_ACCOUNTS, USE_CREDENTIALS ver:1.1.1
04-27 21:52:22.503  18`

Looks from [this](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/master/src/src/com/microsoft/aad/adal/BrokerProxy.java) that more permissions need to be set in the AndroidManifest by the plugin to utilize the broker. When I added those permissions to plugin.xml the error went away.

**Comment by sgrebnov** [comment]
@joshgav Thx for the patch! Closing this issue
