### ISSUE TITLE
Plugin doesn't allow me to signout on Android 5.0 and 5.1

### ISSUE THREAD

**Issue by Prince08Lamba** [AzureAD/azure-activedirectory-library-for-cordova#41]
ms-ADAL Plugin doesn't works for Android 5.0 and 5.1 . Please help me out

**Comment by sgrebnov** [comment]
Hey @Prince08Lamba, could you please describe the problem in more details

**Comment by Prince08Lamba** [comment]
Hey @sgrebnov Acutally when i login in my account and acquire token successfully and then again if i click on aquire token  and try to login with different account and click on forgot password and then click on back button it again give me token of old logged in account 
![save1](https://cloud.githubusercontent.com/assets/14884622/13055541/eaf384c4-d435-11e5-9c0e-8993f69e0545.jpg)
![save2](https://cloud.githubusercontent.com/assets/14884622/13055553/f97f6ef4-d435-11e5-8c42-ff8655b239ca.jpg)

**Comment by Prince08Lamba** [comment]
hey @sgrebnov as shown above is there is any way removed signed in Accounts so that they always need password for token .Thanks in advance

**Comment by sgrebnov** [comment]
Thank you for the details, I'll take a look once I have a chance.

**Comment by Prince08Lamba** [comment]
Thanks @sgrebnov. I will wait for your reply .Thanks In advance

**Comment by sgrebnov** [comment]
Could you please try using `authContext.tokenCache.clear()` to see if it can help

**Comment by Prince08Lamba** [comment]
@sgrebnov authContext.tokenCache.clear() removes token from clientSide (My App side) but cache is on Azure Side .So how i can remove cache from Azure AD side

**Comment by sgrebnov** [comment]
I think you should do `XmlHttpRequest` (or open `InAppBrowser` instance) pointing to the following url.
```
https://login.windows.net/{tenantid or "common"}/oauth2/logout?post_logout_redirect_uri={URL}
```
http://stackoverflow.com/a/23823129/255654

**Comment by sgrebnov** [comment]
We had similar signout functionality using XmlHttpRequest but it was removed as application specific and marked as out of scope. We will document this as recommendation on home page as part of the next docs update circle.

**Comment by sgrebnov** [comment]
Resolving as out of plugin scope
