### ISSUE TITLE
ADAL native libraries are out of date

### ISSUE THREAD

**Issue by Chuxel** [AzureAD/azure-activedirectory-library-for-cordova#44]
ADAL Android appears to reference 1.1.1 while 1.1.12 is current. I suspect iOS and Windows are also out of date.

We should update to the latest versions of the native libraries for the plugin given it entirely depends on the underlying native implementations of the ADAL libraries.

**Comment by sgrebnov** [comment]
@vladimir-kotikov could you please help wrt Android and iOS. Windows is already up to date (updated a few days ago)

**Comment by sgrebnov** [comment]
Completed (iOS: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/da1f116ae7d96da96e90f184665b43e401164ada, Android: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/64e5563acac90111d39773f3259d072ae1b83e65)

**Comment by sgrebnov** [comment]
Reopening since there are two different libs for windows are used (netcore45 and wpa) and only one has been updated to the latest.

**Comment by sgrebnov** [comment]
Updated Windows (netcore45): https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/cf880e78ea0d1b3ba4d069a414925f99e378678e
