### ISSUE TITLE
UserInfo example

### ISSUE THREAD

**Issue by chazwoza** [AzureAD/azure-activedirectory-library-for-cordova#55]
Hi,
After authenticating I want to access various information about the authenticated user. Can you give any examples of how to do this?

In ADALJS, it seems to set up a "UserInfo" object under the root scope which is accessible in my html templates for stuff like "ng-show="userInfo.isAuthenticated".

Is it possible to do the same with ADAL for Cordova?

I can see there is a UserInfo.js file ... but can't figure out how its used.

**Comment by sgrebnov** [comment]
To retrieve user info you should make _authContext.acquireTokenSilentAsync_ method call. Information required will be available as part of authentication result (_authResponse.userInfo_), see here:
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blame/8b5664b61d02da58d8876ff3ca9eb528e8778709/README.md#L37

You can also take a look on the following unit tests: 
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/tests/www/tests.js#L177

Alternative way (not recommended) is to use `authContext.tokenCache.readItems()` to retrieve cached items which should have this information as well (see https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blame/8b5664b61d02da58d8876ff3ca9eb528e8778709/README.md#L123), but you will need to figure out which item represents currently authenticated user

**Comment by sgrebnov** [comment]
@chazwoza, I'm closing this issue as information above should answer your question, feel free to re-open if you still need more help
