### ISSUE TITLE
Windows 10 mobile: AuthenticationContext: type is not constructible

### ISSUE THREAD

**Issue by gleborgne** [AzureAD/azure-activedirectory-library-for-cordova#56]
When running on Windows 10 mobile (a 950XL), everything is working fine if debugging with Visual Studio, but if running the app without debug (just launching it on the device), any call to ADAL results in an error "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext: type is not constructible"

**Comment by sgrebnov** [comment]
I'll verify this, can you answer the following questions pls

1.  what ADAL plugin version do you use?
2.  what Visual Studio version do you have installed (including update version) 
3.  are you using Visual Studio Cordova Tools or command line to create the app

**Comment by GaryMcAllister** [comment]
As below

> On 12 Apr 2016, at 09:26, Sergey Grebnov <notifications@github.com> wrote:
> 
> I'll verify this, can you answer the following questions pls
> 
> what ADAL plugin version do you use?

Version 0.6.2

> what Visual Studio version do you have installed (including update version)

2015 update 2
> are you using Visual Studio Cordova Tools or command line to create the app

I'm using Cordova tools

**Comment by sgrebnov** [comment]
I've tried to reproduce this issue on Lumia 1520, Windows Mobile 10 (10.0.10586.122) using VS 2015 Community Update 2, plugin version 0.6.2 and I don't see this problem: after launching application on device without debugger and calling ADAL functions everything worked correct - I've tried creating test app using Cordova CLI and VS Cordova Tools (same result).

Does this repro on blank cordova app w/ ADAL plugin added? Or this require some special logic?

**Comment by sgrebnov** [comment]
Please confirm you are using Windows10 target to run on Windows Mobile 10, not Windows Phone 8.1

**Comment by GaryMcAllister** [comment]
Windows 8.2, not 10 deployed on a Windows 8.2 phone.

Universal app.

**Comment by gleborgne** [comment]
I had it when targeting Windows 10, with no special logic other than standard connection. It works on Windows 8.1 devices if I change target

**Comment by GaryMcAllister** [comment]
Ok Thanks.. Will retest and let you know what my issue is.

**Comment by sgrebnov** [comment]
@gleborgne still unable to reproduce. I have only  Lumia 1520, Windows Mobile 10 (10.0.10586.122) for testing. Do you still have problem getting this working? If so, could you please try running it on Windows Phone 10 emulator to see if you have repro there as well (if so, it could be tools specific).

**Comment by sgrebnov** [comment]
This issue is inactive for a while, please re-open, if the problem is still actual.
