### ISSUE TITLE
Cache is always empty on Android 4.2.x and below

### ISSUE THREAD

**Issue by sgrebnov** [AzureAD/azure-activedirectory-library-for-cordova#60]
As reported here:
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/54#issuecomment-208380183

Caching support for Android Api level 17 and below (<= 4.2.x) requires some extra work:
AzureAD/azure-activedirectory-library-for-android#80

**Comment by Klotair** [comment]
Hi, thanks you for fixing this :)

I tried the 0.7.0 version today and I get this error:

> :compileDebugJavaWithJavacC:\workspace\VIGI-PROCHE\silver-platform\VigiProche\src\platforms\android\src\com\microsoft\aad\ad
al\CordovaAdalPlugin.java:162: error: incompatible types: List<TokenCacheItem> cannot be converted to ArrayList<TokenCacheIt
em>
                ArrayList<TokenCacheItem> tokensForUserId = ((ITokenStoreQuery)cache).getTokensForUser(userId);
                                                                                                      ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

> FAILURE: Build failed with an exception.

> * What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

> * Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

Any idea why I does not work here ?
Thanks

**Comment by Klotair** [comment]
Hi, thanks for fixing this :)

I tried the 0.7.0 today and I get this error when building an apk :


>  src\platforms\android\src\com\microsoft\aad\ad\CordovaAdalPlugin.java:162: error: incompatible types: List<TokenCacheItem> cannot be converted to ArrayList<TokenCacheIt
em>
                ArrayList<TokenCacheItem> tokensForUserId = ((ITokenStoreQuery)cache).getTokensForUser(userId);
                                                                                                      ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

Any idea why it does not work here ? 
Thanks !

**Comment by Klotair** [comment]
Ok, it seems to work :dancer: 
I just fix the java compile error with this lines :
 
From the line 162 in CordovaAdalPlugin.java
```
 Iterator<TokenCacheItem> tokensForUserId = ((ITokenStoreQuery)cache).getTokensForUser(userId).iterator();
               if (tokensForUserId.hasNext()) {
                   // Try to acquire alias for specified userId
                   userId = tokensForUserId.next().getUserInfo().getDisplayableId();
               }
```

There is still a bug in the current 0.7.0 version which break the compilation for android.
Thanks
