### ISSUE TITLE
Add validateAuthority flag support when creating AuthenticationContext using constructor

### ISSUE THREAD

**Issue by didierjeanson** [AzureAD/azure-activedirectory-library-for-cordova#66]
Sample cordova communicating with an API secured with ADFS (authority=https://myadfsserver/adfs) (built with VS2015 Update2) is working fine with iOS devices.
Same application is not working when **selecting Windows Tablet (8.1/10) or Windows Phone 10 (emulator). When calling app.context.acquireTokenSilentAsync the following error is returned Authority validation is not supported for this type of authority (at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator..ctor)**.
Same code but with authority=https://login.windows.net/common (AAD) is working on Windows devices.

**Comment by didierjeanson** [comment]
More details on the problem with ADFS and Windows clients. 
Turning off Authority validation with Microsoft.ADAL.AuthenticationContext (authority, false) has no effect in Cordova; the ADALProxy.js does not receive the args[1] and use the default value (which is true). 
Forcing the value to false (in debug step by step) raise the following exception: The browser based authentication dialog failed to complete. Access is denied.

**Comment by didierjeanson** [comment]
I found a workaround by forcing the default value of validateAuthority to false in ADALProxy.js (after line 48) for the Windows Platform. I haven't found out why the args[1] is not received.

**Comment by sgrebnov** [comment]
@didierjeanson, please see if `Microsoft.ADAL.AuthenticationContext.createAsync(authority, validateAuthority)` method works for you as there is currently possible to specify validation flag via  this method only.

https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/8b5664b61d02da58d8876ff3ca9eb528e8778709/www/AuthenticationContext.js#L47
```
Microsoft.ADAL.AuthenticationContext.createAsync('https://myadfsserver/adfs', false)
    .then(function(authContext) {
        app.context = authContext;
        app.context.acquireTokenSilentAsync(...)
    }, function(err) {
        // handle Error
    });
```

PS.The Microsoft.ADAL.AuthenticationContext constructor has been added for simplicity and does not support that flag. I'll see how we should improve related logic and docs.

**Comment by GaryMcAllister** [comment]
This works fine for me.

**Comment by sgrebnov** [comment]
After internal discussion the agreement was to add validation flag support when creating AuthenticationContext using constructor as well so that you will be able to pass validateAuthority flag.
```
var context = new Microsoft.ADAL.AuthenticationContext(authority, validateAuthority);
```

PS. @GaryMcAllister thx for confirming that workaround is working for you!

**Comment by didierjeanson** [comment]
I also confirmed that it works (not using the constructor). I am able to remove the workaround.
Thanks for adding the flag in the constructor in a future release.
@sgrebnov thanks for your help
