### ISSUE TITLE
Cannot compile ios target with adal cordova library and space in config.xml's name property

### ISSUE THREAD

**Issue by EeKay** [AzureAD/azure-activedirectory-library-for-cordova#7]
Tooling used:
Macbook pro with OS X Yosemity 10.10.3, Cordova CLI 5.0.0, NPM 2.7.4, Node v0.10.28
Xcode 6.3.1, Command Line Tools (OS X 10.10) for Xcode 6.3.1

Steps to reproduce:
- create new project with
$ cordova create adalbuilderrortest com.example.adaltest 'Adal Testapp'
- go to adalbuilderrortest/www
- add plugin via
$ cordova plugin add cordova-plugin-ms-adal
- add platform ios via
$ cordova platform add ios
- try to build and/or emulate ios target
$ cordova build ios  (or cordova emulate ios)

The resulting error is:
 xcodebuild[30309:244944] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon in dictionary on line 513. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolon to debug.

Currently there are two "tests" to see if one can get the ios target building again:
1) removing the adal plugin  (not an option for me)
2) removing the space between Adal and Testapp in the config.xml's > widget > name property 

I've been inspecting the hook scripts and other stuff but cannot really find a cause for this myself.
Hope you can check this out!?

**Comment by EeKay** [comment]
I have fixed this; seems the space in my project's name was causing the issue in combination with the configureEntitlementsIos.js script... I'll send in a pull-request in a couple hours to address this.

At least we can have spaces in the project names then ;)

**Comment by EeKay** [comment]
The pull request fixing this issue has been issued.. Pull request https://github.com/AzureAD/azure-activedirectory-library-for-cordova/pull/8

**Comment by sgrebnov** [comment]
@EeKay Thx for the patch! Closing this issue
