### ISSUE TITLE
Support for 'browser' cordova platform

### ISSUE THREAD

**Issue by faxedhead** [AzureAD/azure-activedirectory-library-for-cordova#72]
### Issue Description
Currently this plugin appears to not support the 'browser' cordova platform.  When a browser app is run using this plugin, the plugin is not loaded and the browser shows message:

`'ReferenceError: Microsoft is not defined'`

It would be really helpful to enable support for this platform.  Is this easy to achieve?

### Repro Environment Details
1. Installed plugin version: 0.7.1
2. Target Platform: 'Browser'
3. Test device and OS version: for example, Chrome 49 on Windows 7 x64 desktop.
4. Tools: Cordova CLI and Ionic CLI

**Comment by sgrebnov** [comment]
The plugin relies on native implementation for each target platform, for _browser_ we can see if we can use [ADAL for JavaScript](https://github.com/AzureAD/azure-activedirectory-library-for-js/). I see that proposed functionality could be valuable, but browser support is currently low priority and there is no defined deadline for this.

**Comment by SPDoctor** [comment]
For browser target you would need to use implicit flow and this is how ADAL.js does it. I don't see too many plug-ins bothering to support the browser target. 

Probably more useful would be support for the Ripple emulator. That requires the "tinyHippos" check and then emulate the native behaviour.
