### ISSUE TITLE
Error: "Error occured while executing native method." with WP8.1 device

### ISSUE THREAD

**Issue by tumetus** [AzureAD/azure-activedirectory-library-for-cordova#73]
Steps when using the sample application:
1. Tap "create authentication context"
2. Tap "aquire token"
Loading screen appears for few seconds and then goes back to app with error message "Error occured while executing native method.". This only occurs when deployed on a Windows Phone 8.1 device. Plugin and the sample app work fine with emulator, Windows 10 Mobile, Android and iOS devices.

Tested with Lumia 820, Lumia 830 and Lumia 920 devices.
I am using Cordova from command line (6.1.1) and deploying the application with Visual Studio 2015. 
Plugin version 0.7.1. 
I have adal-use-corporate-network set to true.
I am running Windows 8.1 Pro on my PC.

![wp_screenshot](https://cloud.githubusercontent.com/assets/3472062/15314624/bbb9d040-1c1b-11e6-9821-eac25ed6f73e.png)

**Comment by sgrebnov** [comment]
@daserge, could you please clarify the following quirk (if you remember) - does it answers behavior reported - is this error expected or you should see login popup?

> ADFS and SSO options for Windows Phone 8.1 is not supported for now

**Comment by daserge** [comment]
@tumetus, are there any additional details if you set a breakpoint to this line https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/src/windows/ADALProxy.js#L124?
@sgrebnov, the issue on Windows Phone 8.1 & ADFS was initially because of the 2148270105 error ([INET_E_INVALID_CERTIFICATE](https://msdn.microsoft.com/library/ms775145%28v=vs.85%29.aspx)).

**Comment by tumetus** [comment]
@daserge details of result variable are in the screenshot below.

![result](https://cloud.githubusercontent.com/assets/3472062/15420226/0b7244e6-1e74-11e6-8759-a6be26ed5404.PNG)

**Comment by tumetus** [comment]
Any updates on this matter?

**Comment by daserge** [comment]
@tumetus, try looking into these threads:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/76f32643-593f-4109-9122-e266594a5444/troubles-with-client-certificates-in-windows-phone-81-webviews?forum=wpdevelop
https://blogs.windows.com/buildingapps/2013/09/06/updating-your-javascript-apps-to-use-the-new-windows-web-http-api/ (not sure whether native or js HttpClient usage will help)

**Comment by tumetus** [comment]
Thanks for your response @daserge ! Unfortunatelly I am not sure if I understand this correctly. So should I make just a plain get request to the authority url before calling aquireToken?

**Comment by sgrebnov** [comment]
Please see some related information regarding WP8.1/SSO support from corresponding group. So looks like the only potential way to fix this is to use HttpClient based trick described [here](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/76f32643-593f-4109-9122-e266594a5444/troubles-with-client-certificates-in-windows-phone-81-webviews?forum=wpdevelop) and [here](Error occured while executing native method), but I'm not sure this will work as I never tried this. I'm closing this issue as we don't support SSO for WP8.1 officially and will see how to improve corresponding error message (as ''Error occured while executing native method" is not informative)

> The Phone[WP8.1] has never had a certificate selection dialog/prompt to let the user select from a list of client certificates, so the WebView cannot prompt the user to select from a list of Client Certs. 
> 
> For the Phone, the app/developer will have to set the client certificate programmatically. But, the WebView control by itself does not expose a method or property to set a client certificate, so programmatic setting of client certificates directly using WebView control becomes a challenge.
