### ISSUE TITLE
Improve error reporting: add error codes, more informative and consistent errors

### ISSUE THREAD

**Issue by khalidaw** [AzureAD/azure-activedirectory-library-for-cordova#74]
### Issue Description
(IOS)

Error is usually null

**No Connection:**
error: null
errorDescription: "The Internet connection appears to be offline."
statusCode: 2

**Auth not right:**
details: Object
error: "invalid_resource"
errorDescription: "AADSTS50001: The application named google was not found in the tenant named campus.technion.ac.il. This can happen if the application ha…"
statusCode: 2

**User need to sign in again:**
error: null
errorDescription: "The user credentials are need to obtain access token. Please call the non-silent acquireTokenWithResource methods."
statusCode: 2

Am afraid to use errorDescription cause it will change when localizing the app.

**Comment by khalidaw** [comment]
Okay, I understood now from code that error is protocol code.

Is there any option to have error.code?

**Comment by sgrebnov** [comment]
@khalidaw are you looking for this change across all platforms or iOS only? - I've reviewed what native libraries provide and there is nothing similar to error code available on Android for example, so we won't be able to implement it on all platforms.

As per iOS, we can replace (https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/src/ios/CordovaAdalUtils.m#L46
)
```
   [dict setObject:ObjectOrNull(obj.protocolCode) forKey:@"error"];
```
with 
```
  [dict setObject:ObjectOrNull(obj.code) forKey:@"error"];
```
as error `code` is much more informative and could be used to detect main error causes.

TODO: review how `azure-activedirectory-library-for-js` handles errors and if there is any special code

**Comment by sgrebnov** [comment]
Closing as there is no response for 3 weeks. @khalidaw please re-open if this is still actual.

**Comment by khalidaw** [comment]
Hi,

Thanks for the reply :)

Actually we currently support android also, and maybe windows in the future.

I think its good to have a shared interface for errors, for the all platforms, which can return information like:
"AD_USER_CREDENTIALS_IS_NEEDED"

**Comment by sgrebnov** [comment]
I'm on the same page to have consistent error codes across all platforms, I will keep this work item open in our internal backlog so that we can improve this in the future; The only thing here is that we rely on native SDKs so corresponding functionality must be added there first (error codes or logic to detect common errors/cases).

**Comment by sgrebnov** [comment]
Added logic to report error code from native layer to JS. See [err.code](https://github.com/AzureAD/azure-activedirectory-library-for-cordova#handling-errors). Support of iOS, Android, Windows. Let me know you have any problem
