### ISSUE TITLE
Android Permissions

### ISSUE THREAD

**Issue by galvanu** [AzureAD/azure-activedirectory-library-for-cordova#78]
### Issue Description
According to the plugin.xml file I see that the required permissions by the plugin are:
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
<uses-permission android:name="android.permission.MANAGE_ACCOUNTS" />
<uses-permission android:name="android.permission.USE_CREDENTIALS" />
```

the first two are fine but I wonder why the last three are needed?
In addition I look at the [native sdk](https://github.com/AzureAD/azure-activedirectory-library-for-android) and it looks like only the INTERNET and ACCESS_NETWORK_STATE are required?

Can you please give sone info about why the additional permissions added here?
Thanks.

**Comment by sgrebnov** [comment]
I believe this was added initially to provide single SSO support (https://github.com/AzureAD/azure-activedirectory-library-for-android#broker). 
```
If target version is lower than 23, calling app has to have the following permissions declared in manifest(http://developer.android.com/reference/android/accounts/AccountManager.html):
GET_ACCOUNTS
USE_CREDENTIALS
MANAGE_ACOUNTS
```
Starting from target API 23 those permissions are requested programmatically if user specified `Microsoft.ADAL.AuthenticationSettings.setUseBroker(true)` - https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/src/android/CordovaAdalPlugin.java#L263

**Comment by sgrebnov** [comment]
Please re-open if you have more questions
