### ISSUE TITLE
Informative errors code

### ISSUE THREAD

**Issue by khalidaw** [AzureAD/azure-activedirectory-library-for-cordova#79]
Hi,

Native libraries for ADAL includes information when errors happens.

for ex: "AD_USER_CREDENTIALS_IS_NEEDED"

Cordova plugin doesn't return this error (only error string which can't rely on)

IOS, Android

Thanks

**Comment by sgrebnov** [comment]
I think we should keep all discussions in single/original thread so closing this one on favor of  https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/74
