### ISSUE TITLE
ADAL is not working for first time login in cordova windows 10 platform.. 

### ISSUE THREAD

**Issue by ashwin4av** [AzureAD/azure-activedirectory-library-for-cordova#80]
# ADAL is not working for first time login in cordova windows 10 platform
@tacoadmin @azureAD
We have installed ADAL plugin and while trying to login the bellow error message is coming for first  time login (2 to 3 times) after some time it is login successfully. 

Error we are facing is  :  

> **## "We can't connect to service right now. Check your internet connection or try this again later"**

## Repro Environment Details
1. Installed ADAL plugin version: version 0.7.1
2. Target Platform: Windows 10.0
3. Test device and OS version: Windows Mobile 10.0 mobile`, `Windows 10.0 Desktop x64`
4. Using cordova tools 6.1.1 CLI
3. SSO option is enabled.

Plugin Screen : 
![image](https://cloud.githubusercontent.com/assets/17904195/16376479/0f42116e-3c7e-11e6-88ea-f0a0abe330b7.png)

Code Snippet : 
![image](https://cloud.githubusercontent.com/assets/17904195/16376543/5b1a6bea-3c7e-11e6-8f94-b26211b5c26c.png)

Error Screen : 
![image](https://cloud.githubusercontent.com/assets/17904195/16376454/f53be27c-3c7d-11e6-918b-f7c03dee2f52.png)

## Please help us on this issue. Is there any alternative plug in for adal. share us sample or need to add anything in code.? . 

@azureAD

Thanks in advance 
Ashwin.

**Comment by sgrebnov** [comment]
Unable to reproduce, @ashwin4av could you please verify you have repro using standard sample app as well.

```
cordova create adalTest && cd adalTest
cordova plugin add https://github.com/AzureAD/azure-activedirectory-library-for-cordova/
xcopy plugins\cordova-plugin-ms-adal\sample\* www /Y /E
cordova platform add windows
cordova run windows --archs=x64 -- --appx=uap
```

**Comment by sgrebnov** [comment]
Please re-open if this is still actual.

**Comment by afourney** [comment]
I'm experiencing the same issue. 

Specifically, we see the "Can't connect" screen after the redirect that occurs upon entering one's email address.  This *only* occurs for users who are connected to our corporate WIFI network on Windows 10.
