### ISSUE TITLE
User display id looks bad with utf8 characters

### ISSUE THREAD

**Issue by khalidaw** [AzureAD/azure-activedirectory-library-for-cordova#84]
Display id that contains utf8 characters - for example áškhalidáš (czech characters) - is received bad after interactive login:

[
![screen shot 2016-08-01 at 21 27 35](https://cloud.githubusercontent.com/assets/11428454/17304560/db7c6fb0-582e-11e6-99ef-5c3c4917e6ca.png)
](url)

Env: typescript, both IOS and Android

**Comment by khalidaw** [comment]
Please note that I was able to solve this by UTF8 decoding for the display id, am not sure if you should do this in your code.

**Comment by sgrebnov** [comment]
Thank you @khalidaw! I'll take a look

**Comment by sgrebnov** [comment]
I've created a test user w/ the same name and confirm this issue:
1.  http://jwt.calebb.net/ parses jwt token returned by ADAL service correctly (including non-us characters): `name: "áškhalidáš",`
2.  our [parseJWT](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/8b5664b61d02da58d8876ff3ca9eb528e8778709/www/utility.js#L585)  implementation does not handle encoding

**Comment by sgrebnov** [comment]
Fixed by https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/f37aa481b7628864adc31cd15feb57d2d6649ed8, to be included into the next plugin release. @khalidaw , please see if you will need to update client app logic after release and bumping adal version.
