### ISSUE TITLE
Using cordova-plugin-ms-adal on vanilla ionic2 project does not recognize Microsoft namespace

### ISSUE THREAD

**Issue by alvaradojl** [AzureAD/azure-activedirectory-library-for-cordova#86]
### Issue Description
After setting up a vanilla ionic2 project and updating home.ts to include a login function being called by a button in home.html with the following line of code:
` let authContext =  new Microsoft.ADAL.AuthenticationContext("https://login.microsoftonline.com/common");`

There is a run-time exception with the message:

> Microsoft is not defined.

### Repro Environment Details
1. Installed plugin version:  cordova-plugin-ms-adal 0.7.1 "ADAL for Cordova"
2. Target Platform: Android
3. Test device and OS version: Nexus 9 Android 6
4. Using Cordova CLI 
3. No SSO enabled

**Comment by sgrebnov** [comment]
1. Please double check that you invoke this code after `deviceready` even is fired:
https://cordova.apache.org/docs/en/latest/cordova/events/events.html
Plugins are loaded async and you can't use them before that event is fired.

2. Also, please see if there are no other errors in the browser console.

**Comment by alvaradojl** [comment]
I realized this code does not work on the Android simulator but it does work on the device itself. 
Thanks anyways!

**Comment by ersurajnegi** [comment]
even after adding it in devcie ready , still microsoft is not define run time exception is coming
