### ISSUE TITLE
Android - keep me signed in not hidden

### ISSUE THREAD

**Issue by khalidaw** [AzureAD/azure-activedirectory-library-for-cordova#87]
Hi,

When opening android web view for login, for ms accounts (private), there is a check box with "Keep me signed in" option. 

This doesn't happen on iOS.

while this KMSI option has no meaning on mobile, do you have a way to hide it? maybe through extra query param?

**Comment by sgrebnov** [comment]
I'm looking on the supported [query params](https://azure.microsoft.com/en-us/documentation/articles/active-directory-protocols-oauth-code/) and, unfortunately, don't see anything you can use.

Ping @vibronet  - Vittorio, could you please help here? - Is there a way to control 'Keep me signed in' option?

**Comment by sgrebnov** [comment]
Closing, please re-open if this is still actual.
