### ISSUE TITLE
iOS - Retrieving "Object moved to here" after login

### ISSUE THREAD

**Issue by pkmelee337** [AzureAD/azure-activedirectory-library-for-cordova#88]
### Issue Description
I am retrieving the error "Object moved to here" after login in iOS. Windows Phone and Android works fine. I always used the redirect URL "http://localhost:4400/services/office365/redirectTarget.html". I also tried the URL "http://localhost:4400/services/aad/redirectTarget.html" from the sample but this isn't working either.

### Repro Environment Details
1. Installed plugin version:  latest dev version (0.7.2-dev)
2. Target Platform: for example, iOS
3. Test device and OS version: Multiple devices and simulators
4. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), Visual studio cordova tools latest version.

**Comment by sgrebnov** [comment]
@pkmelee337, could you please see if you have the same issue when using azure-activedirectory-library-for-cordova@0.7.1? We've recently updated ADAL native library for iOS from 1.x to 2.x so this could be the reason (but I don't see this repro on my test setup)
```
cordova plugin add cordova-plugin-ms-adal@0.7.1
```

**Comment by pkmelee337** [comment]
@sgrebnov, I can confirm that this is indeed working, thank you very much. Pity though that I can't use the latest iOS build.

**Comment by pkmelee337** [comment]
Some extra information, I did find out that the "Object moved to here" error only occured when logging in through ADFS.

**Comment by sgrebnov** [comment]
@pkmelee337 , thank you for the info - I'll take a look.

**Comment by sag333ar** [comment]
![Example Image](https://cloud.githubusercontent.com/assets/4737312/17979348/c439ded6-6b17-11e6-8beb-ee3cc6b503a2.gif)
Not working on iOS-9 too. I've to click 2-3 times on `here` button of "Object Moved here" text.

**Comment by sgrebnov** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/7215f9329415149723da85aa8bf67c6e7a0950b6
I've bumped native iOS lib from 2.2.2 to 2.2.4 and the issue went away (I previously had a stable repro w/ 2.2.2).

**Comment by pkmelee337** [comment]
Thank you very much! I can confirm that the problem is solved.

**Comment by sgrebnov** [comment]
Thanks for confirming this! We are working on release so this should be publicly available soon.
