### ISSUE TITLE
Failure to Load Resource - running plugin with Ionic 

### ISSUE THREAD

**Issue by falcon198198** [AzureAD/azure-activedirectory-library-for-cordova#9]
Oops, for got to add the problem here: 
When I pull up the debugger it is complaining that this file is missing. 
Project seems to run fine without it , but it would be nice to get the error resolved. 

Ideas ?, BTW thank's for the awesome plugin . I have it running in Ionic without any problems.  
 
file:///Users/zzzzz/Library/Developer/CoreSimulator/Devices/DF4F351E-3651-4D91-BB86-763DD58A5856/data/Containers/Bundle/Application/B6B51E16-89E3-48BF-88A8-3936B5D62DE1/InsertManagement.app/www/plugins/com.microsoft.aad.adal/www/utility.js.map

**Comment by sgrebnov** [comment]
See the same error in debug tools

![image](https://cloud.githubusercontent.com/assets/981580/8003588/92c696d8-0b81-11e5-910d-1786b2a6b0dc.png)

**Comment by sgrebnov** [comment]
To fix this the following line must be removed: https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/www/utility.js#L604
