### ISSUE TITLE
iOS - Login not working on iOS10

### ISSUE THREAD

**Issue by pkmelee337** [AzureAD/azure-activedirectory-library-for-cordova#90]
### Issue Description
I have exactly the same error message as described here "https://github.com/AzureAD/azure-activedirectory-library-for-objc/issues/717". It looks like the issue is fixed with this pull-request which is merged: https://github.com/AzureAD/azure-activedirectory-library-for-objc/pull/713 20 days ago. Is it possible to merge the latest version of iOS to the cordova plugin? Problem is it probably will come up with the error I found in issue #88 

### Repro Environment Details
1. Installed plugin version:  (Have you tried installing the latest plugin version to ensure this has not already  been fixed?)
0.7.1
2. Target Platform: iOS 10
3. Test device and OS version: iPhone 6 and emulator with iOS 10
4. Are you using Cordova from command line or special Cordova IDE: Visual Studio Cordova Tools

**Comment by khalidaw** [comment]
I think this must be a high priority for next release.

We do see this error a lot in telemetry, happens for more than half of the people with iOS 10.

**Comment by sgrebnov** [comment]
Thanks for reporting this along w/ the link to fix in native lib, to be addressed soon.

**Comment by khalidaw** [comment]
I tested the code in master, it workes with iOS 10. (some where you upgraded to ADAL > 2, and no issue there)

**Comment by sgrebnov** [comment]
I don't see [the patch](https://github.com/AzureAD/azure-activedirectory-library-for-objc/commit/9fdc4754788f7361b0e5a5b869eb954ebb13c308) has been included to 2.2.2 (what we use in master), but I'm looking on the 2.2.2 codebase and confirm there is no `didFailWithError`  call in `stopLoading` method which was causing iOS 10 Beta 2+ issue in 1.2.x. So we should be fine.
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/2.2.2/ADAL/src/urlprotocol/ADURLProtocol.m#L151
