### ISSUE TITLE
Launching broker(Authenticator) app from iOS

### ISSUE THREAD

**Issue by ramaguduri** [AzureAD/azure-activedirectory-library-for-cordova#95]
### Issue Description
I have downloaded the sample shared in the repository and followed the instructions to create ADALSample cordova project. I am trying to debug this application from xcode on a connected device where MS authenticator application is installed. When I click on 'AcquireToken' on the menu it keeps opening the embedded browser but not the authenticator application. I made sure 'LSApplicationQueriesSchemes' was added in plist with 'msauth' and verified it is available through 'http://ngcordova.com/docs/plugins/appAvailability/' cordova plugin.

Same sample is working with Android when I added 'Microsoft.ADAL.AuthenticationSettings.setUseBroker(true);'

I checked the 'ADAuthenticationContext.h, 'ADCredentialsType' is set to 'AD_CREDENTIALS_AUTO' which by description should detect the authenticator app by –canOpenURL:.

### Repro Environment Details
1. Installed plugin version:  0.8.0
2. Target Platform: iOS
3. Test device and OS version: iPhone 6 plus, OS 9.3.3
4. Cordova CLI - 6.3.1, Cordova iOS - 4.2.1
5. Authenticator app - 4.0.3

**Comment by greybax** [comment]
I think that I have the similar behavior. Let me describe it by steps:

1. Try to login page in my app
2. Get notification in Authenticator app on this iPhone (device where I've tried to login). 
3. Go to Authenticator app and activate app.
4. Come back to our app
5. Don't get any token in this app

If notification comes to another phone (for example on my android device) and I didn't collapse my app access token comes successfully after activation via Authenticator app

**Comment by ramaguduri** [comment]
@greybax 

What do you mean when you try to login page in the app? Which API are you using from the library? I'm using 'acquireTokenAsync' which launches the embedded browser.

And I dont get any notification on the Authenticator app.

**Comment by greybax** [comment]
I'm using this method in ```js```
```
authenticate: function (authCompletedCallback) {
        app.context = new Microsoft.ADAL.AuthenticationContext(authority);
        app.context.tokenCache.readItems().then(function (items) {
            if (items.length > 0) {
                authority = items[0].authority;
                app.context = new Microsoft.ADAL.AuthenticationContext(authority);
            }
            // Attempt to authorize user silently
            app.context.acquireTokenSilentAsync(resourceUri, clientId)
                .then(authCompletedCallback, function () {
                    // We require user cridentials so triggers authentication dialog
                    app.context.acquireTokenAsync(resourceUri, clientId, redirectUri)
                        .then(authCompletedCallback, function (err) {
                            app.error("Failed to authenticate: " + err);
                        });
                });
        });
    },
```

and call it in on ```onDeviceReady```:

```
onDeviceReady: function () {
        app.authenticate(function (authResponse) {
            console.log("Token acquired: " + authResponse.accessToken);
            console.log("Token will expire on: " + authResponse.expiresOn);            
        }, function (err) {
            console.log("Failed to authenticate: " + err);
        });
    },
```

**Comment by ramaguduri** [comment]
Yep that is from the sample and I am using the same to test.

I just changed the 'resourceUri, clientId, redirectUri'.

Did you have to change anything in Cordova application to get the notification for Authenticator app other than adding 'LSApplicationQueriesSchemes' to the plist?

Also I think once you authenticate in the Authenticator app if you have the right re-direct URL scheme as mentioned in this [blog ](https://azure.microsoft.com/en-us/documentation/articles/active-directory-sso-ios/)Authenticator app should invoke your application back, instead of you switching to the application manually.

**Comment by sgrebnov** [comment]
@ramaguduri,  does it work if you use 0.7.1 (public) plugin version? I'm going to investigate this issue before 0.8.0 release.

**Comment by sgrebnov** [comment]
@ramaguduri, I'm running the code and also looking into the source code and in both places I see that `_credentialsType = AD_CREDENTIALS_EMBEDDED;` by default which prevents ADAL from calling to the broker
https://github.com/AzureAD/azure-activedirectory-library-for-objc/blob/dev/ADAL/src/ADAuthenticationContext.m#L103

It was enabled and worked by default previously. Looks like native ADAL library behavior change.

**Comment by sgrebnov** [comment]
Problem here, is due to internal lib implementation if we always set `_credentialsType = AD_CREDENTIALS_AUTO` it will fail for standard urls (not for brokered auth). We should update our implementation to set up this parameter for every api call.

```
 if (!_silent && _context.credentialsType == AD_CREDENTIALS_AUTO && ![ADAuthenticationRequest validBrokerRedirectUri:_redirectUri])
    {
        ADAuthenticationError* error =
        [ADAuthenticationError errorFromAuthenticationError:AD_ERROR_TOKENBROKER_INVALID_REDIRECT_URI
                                               protocolCode:nil
                                               errorDetails:ADRedirectUriInvalidError
                                              correlationId:_correlationId];
        completionBlock([ADAuthenticationResult resultFromError:error correlationId:_correlationId]);
        return;
    }
```

**Comment by sgrebnov** [comment]
`ADAuthenticationRequest validBrokerRedirectUri` is private method so we can't use it so there are two option here: 
1. Add own implementation similar to validBrokerRedirectUri
2. Introduce JS method similar to Android to control this setting (re-use the same JS method as on Android).

**Comment by sgrebnov** [comment]
I was able to get it working by manually adding the following:

plist
```
    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>msauth</string>
    </array>
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLName</key>
            <string>io.cordova.hellocordova</string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>x-msauth-mytestiosapp</string>
            </array>
        </dict>
    </array>
```

CordovaADALPlugin.m
```
authContext.credentialsType = AD_CREDENTIALS_AUTO;
```
js
```
var REDIRECT_URL = "x-msauth-mytestiosapp://io.cordova.hellocordova";
```

The above works for me and I can see that Authenticator app is started and I get authentication token upon successful login.

The problem here is how to make it working via plugin (modify plist according to application bundle and registering unique app scheme)

**Comment by ramaguduri** [comment]
@sgrebnov I was able to get this working after adding the line you mentioned in CordovaADALPlugin.m.

For setting the credentialsType can we leverage the 'Microsoft.ADAL.AuthenticationSettings.setUseBroker(true);' method for IOS as well?

I have modified the plugin.xml to automatically add the 'LSApplicationQueriesSchemes' and 'CFBundleURLTypes'.
If you can create a branch for this I can submit a pull request.

Thanks for the quick turnaround.

**Comment by sgrebnov** [comment]
Adding `Microsoft.ADAL.AuthenticationSettings.setUseBroker(true); ` support should be simple. I'm thinking whether we can automatically detect whether we want to use brokered authentication looking on on the plist info.

Also, we have the following settings files automatically added by our plugin:
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/src/ios/ADALiOS.entitlements

Can we extend it to automatically add required settings?

**Comment by sgrebnov** [comment]
@ramaguduri could you please create a gist w/ the sample config.xml to update plist. I'll use this approach as a backup plan if idea above won't work - add support for `setUseBroker(true)` + document config.xml requirements.

**Comment by sgrebnov** [comment]
I've playing w/ entitlements file we have and if I add the following section
```
	<key>LSApplicationQueriesSchemes</key>
    <array>
      <string>msauth</string>
    </array>
    <key>CFBundleURLTypes</key>
    <array>
        <dict>
            <key>CFBundleTypeRole</key>
            <string>Editor</string>
            <key>CFBundleURLName</key>
            <string>$(CFBundleIdentifier)</string>
            <key>CFBundleURLSchemes</key>
            <array>
                <string>x-msauth-$(CFBundleIdentifier:rfc1034identifier)</string>
            </array>
        </dict>
    </array>
```
It is automatically resolved to what we need in plist
```
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>io.cordova.hellocordova</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>x-msauth-io-cordova-hellocordova</string>
			</array>
		</dict>
	</array>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>msauth</string>
	</array>
```

So we can just document, that the redirect url should be in the following format:
```
x-msauth-{BundleId with dots replaced with dashes}://{BundleId}
```

**Comment by ramaguduri** [comment]
Sweet! I was looking at a way to do it through config.xml with no luck.

This [link ](http://stackoverflow.com/questions/22769111/add-entry-to-ios-plist-file-via-cordova-config-xml) says it has to be done through plugin.xml but we will be hard coding at that point.

**Comment by sgrebnov** [comment]
The following extra section in plugin.xml works for me. See `$(CFBundleIdentifier)` and `x-msauth-$(CFBundleIdentifier:rfc1034identifier)` - they are automatically resolved during build as per your real identifier.
```
        <config-file target="*-Info.plist" parent="LSApplicationQueriesSchemes">
            <array>
                <string>msauth</string>
            </array>
        </config-file>

        <config-file target="*-Info.plist" parent="CFBundleURLTypes">
            <array>
                <dict>
                    <key>CFBundleTypeRole</key>
                    <string>Editor</string>
                    <key>CFBundleURLName</key>
                    <string>$(CFBundleIdentifier)</string>
                    <key>CFBundleURLSchemes</key>
                    <array>
                        <string>x-msauth-$(CFBundleIdentifier:rfc1034identifier)</string>
                    </array>
                </dict>
            </array>
        </config-file>
```

**Comment by sgrebnov** [comment]
I think we cam use the following code to determine whether we should proceed w/ brokered auth or not. It seems to work well. I'm going to add documentation and commit support for brokered auth soon.
```
            // `x-msauth-` redirect url prefix means we should use brokered authentication
            // https://github.com/AzureAD/azure-activedirectory-library-for-objc#brokered-authentication
            authContext.credentialsType = (redirectUri.scheme && [redirectUri.scheme hasPrefix: @"x-msauth-"]) ?
                AD_CREDENTIALS_AUTO : AD_CREDENTIALS_EMBEDDED;
```

**Comment by ramaguduri** [comment]
Thanks for the help. Right now I will continue using the workaround, please update this issue when it is available on the release.

**Comment by sgrebnov** [comment]
I've just pushed a fix for this to master, please let me know whether it works. See documentation update to make sure you use the right redirect uri.

https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/8192ef4a647edf5d65f67d601847fbeed0cb323b
