### ISSUE TITLE
#import <ADAL/ADAL.h> file not found

### ISSUE THREAD

**Issue by greybax** [AzureAD/azure-activedirectory-library-for-cordova#96]
### Issue Description
    > cordova platform add --save iOS
    > cordova build ios

In CordovaAdalPlugin.m got exception `#import <ADAL/ADAL.h>` file not found

### Repro environment details
1. Installed plugin version: 0.8.0
2. Target Platform: iOS
3. Cordova CLI - 6.3.1, Cordova iOS - 4.2.1

**UPD:** my bad. didn't compile it properly. Now it's ok. **Issue can be closed**

**Comment by sgrebnov** [comment]
Thanks for update!
