### ISSUE TITLE
Cannot login to ADFS on iOS 10

### ISSUE THREAD

**Issue by GaryMcAllister** [AzureAD/azure-activedirectory-library-for-cordova#97]
Unable to login using ADFS 3.0 and the ADAL, authentication automatically gets cancelled.

**Comment by sgrebnov** [comment]
Which plugin version do you use?

**Comment by GaryMcAllister** [comment]
8.0

**Comment by GaryMcAllister** [comment]
Hi... have you confirmed this is a bug?.. any idea when it will be resolved?.. getting pressure in my org. 😞

**Comment by sgrebnov** [comment]
@GaryMcAllister we are starting actively investigating this problem (not tried to repro yet)..  will keep you updated. Ping @vladimir-kotikov

Could you please see if turning off `validateAuthority` helps? - I saw similar issue reported recently on  StackOverflow:

```
var context = new Microsoft.ADAL.AuthenticationContext(authority, false);
```

**Comment by sgrebnov** [comment]
Also, starting from 8.0 there is special `err.code` field included in error instance which should contain specific rejection reason returned by native library. Could you please post your error including this field here. For more details: https://github.com/AzureAD/azure-activedirectory-library-for-cordova#handling-errors

**Comment by GaryMcAllister** [comment]
It's already off ... 😞

**Comment by GaryMcAllister** [comment]
Will do, thanks.

**Comment by vladimir-kotikov** [comment]
I will try to reproduce the issue once I have test ADFS infrastructure set up. Will keep you posted.

**Comment by GaryMcAllister** [comment]
The issue I have is that I have multiple AD Trusts setup and when you select any organisation the login page just assumes a cancellation of the login process.

**Comment by GaryMcAllister** [comment]
I've looked at the error codes and I get a statusCode 2 and a description of "The operation was cancelled"

**Comment by GaryMcAllister** [comment]
8.2 seems to have fixed my issue (thanks).
